import {mkdirSync,readFileSync,existsSync} from 'node:fs';import {writeFile,rename,copyFile} from 'node:fs/promises';import {resolve,join} from 'node:path';
import type {ExperienceStore} from '../memory/store';import type {LiveJournal} from '../journal/store';import type {Encounter} from '../../shared/observation';import type {ResearchProposal} from '../../shared/journal';
import {EXTERNAL_POLICY as P,REFERENCE_PAGES,RESEARCH_PAGES,approvedPage,coinAddress} from './external-policy';
import {CORPUS} from '../memory/corpus';
interface Destination {url:string;title:string;discoveredAt:string;from?:string;terms:string[];lastVisit?:string;visits:number;failedUntil?:string;lastOutcome?:string}
interface Choice {id:string;at:string;from:string;to:string;objective:string;owner:ResearchProposal['owner'];memoryIds:string[];baselineUrl:string;memoryChangedSelection:boolean;questionId?:string;scores:{url:string;historyScore:number;memoryBonus:number;score:number}[]}
interface State {version:1;destinations:Destination[];recent:{url:string;at:string;visitId:string}[];choices:Choice[];lastUrl?:string;questionVisits:Record<string,string>}
const canonical=(url:string)=>url.split('#')[0].replace(/\/$/,'');
const kind=(url:string)=>coinAddress(url)?'coin':url.includes('ponsfamily')?'explore':url.includes('ethereum.org')?'knowledge':url.includes('blockscout')?'explorer':'research';
export class ExplorationCooldown extends Error {constructor(readonly waitMs:number){super('Approved destinations are cooling down; holding exploration without repeating input.');}}
/** Persistent environment planning, separate from sensory input and motor decoding.
 * Candidate links come from actual approved pages; memory effects have a recorded
 * counterfactual ranking without memory. No random choice or positional reset. */
export class ResearchPlanner {
 readonly root:string;private state:State={version:1,destinations:[],recent:[],choices:[],questionVisits:{}};private writes=Promise.resolve();private ioError?:string;readonly visits=new Map<string,number>();readonly coins=new Map<string,string>();ponsBlocked?:string;private activeChoice?:Choice;
 constructor(runtime:string,readonly memory?:ExperienceStore,readonly journal?:LiveJournal){this.root=resolve(runtime,'exploration');mkdirSync(this.root,{recursive:true});let found=false,loaded=false;for(const file of ['progress.json','progress.previous.json']){if(!existsSync(join(this.root,file)))continue;found=true;try{const state=JSON.parse(readFileSync(join(this.root,file),'utf8')) as State;if(state.version!==1||state.destinations.length>500||!state.destinations.every(d=>approvedPage(d.url)))throw Error();this.state=state;loaded=true;break;}catch{}}if(found&&!loaded)throw Error('Exploration history cannot be loaded; refusing to reset progress');
  // Migrate old anchor aliases without resetting visited history. A section of
  // the same document is not a new encounter or a way around its cooldown.
  const merged=new Map<string,Destination>();for(const d of this.state.destinations){d.url=d.url.split('#')[0];const key=canonical(d.url),prior=merged.get(key);if(prior){prior.visits+=d.visits;if((d.lastVisit??'')>(prior.lastVisit??'')){prior.lastVisit=d.lastVisit;prior.lastOutcome=d.lastOutcome;}if((d.failedUntil??'')>(prior.failedUntil??''))prior.failedUntil=d.failedUntil;if(!prior.title&&d.title)prior.title=d.title;}else merged.set(key,d);}this.state.destinations=[...merged.values()];
  const memories=memory?.list()??[];if(!loaded)for(const m of memories){this.add({url:m.url,title:m.title},undefined);const d=this.destination(m.url)!;d.lastVisit=m.updatedAt;d.visits=Math.max(1,Math.ceil(m.count/8));}
  for(const d of this.state.destinations){this.visits.set(d.url,d.visits);if(coinAddress(d.url))this.coins.set(d.url,d.title);}
  for(const n of CORPUS)this.add({url:n.source,title:n.title},undefined);this.add({url:P.initial,title:'Pons Explore'},undefined);for(const [i,url]of RESEARCH_PAGES.entries())this.add({url,title:'Larval research '+(i+1)},undefined);this.add({url:'https://eth.blockscout.com/blocks',title:'Ethereum block records'},undefined);
  if(!this.state.lastUrl&&memories[0])this.state.lastUrl=memories[0].url;this.save();
 }
 private destination(url:string){return this.state.destinations.find(d=>canonical(d.url)===canonical(url));}
 private add(link:{url:string;title:string},from?:string){if(!approvedPage(link.url)||this.destination(link.url)||from&&canonical(link.url)===canonical(from))return;const url=link.url.split('#')[0],title=link.title.replace(/\s+/g,' ').trim().slice(0,160)||decodeURIComponent(new URL(url).pathname.split('/').filter(Boolean).at(-1)??new URL(url).hostname).replace(/-/g,' '),terms=(title+' '+url).toLowerCase().split(/[^a-z]+/).filter(s=>s.length>3).slice(0,30);if(this.state.destinations.length>=500){const removable=this.state.destinations.filter(d=>!d.visits&&d.from&&canonical(d.from)!==canonical(from??'')).sort((a,b)=>a.discoveredAt.localeCompare(b.discoveredAt))[0];if(!removable)return;this.state.destinations=this.state.destinations.filter(d=>d!==removable);}this.state.destinations.push({url,title,from,discoveredAt:new Date().toISOString(),terms,visits:0});if(coinAddress(url))this.coins.set(url,title);}
 discover(links:{url:string;title:string}[],from?:string){for(const link of links)this.add(link,from);this.save();}
 entered(url:string,visitId=''){const d=this.destination(url);if(d){d.lastVisit=new Date().toISOString();d.visits++;this.visits.set(d.url,d.visits);}this.state.lastUrl=url;this.state.recent.push({url,at:new Date().toISOString(),visitId});this.state.recent=this.state.recent.slice(-30);this.save();}
 result(url:string,status:string){const d=this.destination(url);if(d){d.lastOutcome=status;if(status==='failed')d.failedUntil=new Date(Date.now()+600000).toISOString();}this.save();}
 private save(){const file=join(this.root,'progress.json'),bytes=JSON.stringify(this.state);this.writes=this.writes.catch(()=>{}).then(async()=>{await writeFile(file+'.tmp',bytes);if(existsSync(file))await copyFile(file,join(this.root,'progress.previous.json'));await rename(file+'.tmp',file);this.ioError=undefined;}).catch(()=>{this.ioError='Exploration progress could not be saved; destination changes are held.';});}
 async flush(){await this.writes;}
 next(current?:string){return this.rank(current??this.state.lastUrl??'',undefined,undefined).selected.url;}
 rank(current:string,e?:Encounter,pageText='',ignoreMemory=false){if(this.ioError)throw Error(this.ioError);const now=Date.now(),memories=this.memory?.list()??[],currentMemory=memories.find(m=>canonical(m.url)===canonical(current)),questions=this.journal?.pending()??[],recent=this.state.recent.slice(-4).map(v=>canonical(v.url)),currentKind=kind(current),terms=(pageText+' '+e?.label).toLowerCase();
  let candidates=this.state.destinations.filter(d=>canonical(d.url)!==canonical(current)&&(!this.ponsBlocked||!d.url.includes('ponsfamily'))&&(!d.failedUntil||Date.parse(d.failedUntil)<now));
  const cooled=candidates.filter(d=>!d.lastVisit||now-Date.parse(d.lastVisit)>=180000);if(!cooled.length){const ready=this.state.destinations.filter(d=>canonical(d.url)!==canonical(current)&&(!this.ponsBlocked||!d.url.includes('ponsfamily'))).map(d=>Math.max(d.lastVisit?Date.parse(d.lastVisit)+180000:now,d.failedUntil?Date.parse(d.failedUntil):now));throw new ExplorationCooldown(Math.max(1000,Math.min(...ready)-now));}candidates=cooled;
  const ranked=candidates.map(d=>{const question=questions.find(p=>canonical(p.url)===canonical(d.url)&&(!p.questionId||!this.state.questionVisits[p.questionId]||now-Date.parse(this.state.questionVisits[p.questionId])>=300000)),sameKind=kind(d.url)===currentKind,age=d.lastVisit?(now-Date.parse(d.lastVisit))/60000:120;
   const categoryCount=this.state.recent.slice(-6).filter(v=>kind(v.url)===kind(d.url)).length,categoryLast=Math.max(...this.state.destinations.filter(p=>kind(p.url)===kind(d.url)).map(p=>p.lastVisit?Date.parse(p.lastVisit):0)),neglected=Math.min(40,Math.max(0,(now-categoryLast)/60000-2)*6);
   const historyScore=(d.visits===0?34:Math.min(25,age/3))-Math.min(18,d.visits*.5)-(sameKind?22:0)-categoryCount*8+neglected-(recent.includes(canonical(d.url))?35:0)+(d.from&&canonical(d.from)===canonical(current)?12:0)+(question?45:0);
   const note=CORPUS.find(n=>canonical(n.source)===canonical(d.url)),matches=note?.terms.filter(t=>terms.includes(t))??[],previous=memories.find(m=>canonical(m.url)===canonical(d.url));
   const memoryBonus=ignoreMemory?0:(currentMemory&&matches.length?Math.min(40,matches.length*15):0)-(previous?Math.min(15,Math.log2(previous.count+1)*2):0);
   const memoryIds=ignoreMemory?[]:[...(currentMemory&&matches.length?[currentMemory.id]:[]),...(previous?[previous.id]:[])];return {destination:d,url:d.url,historyScore,memoryBonus,score:historyScore+memoryBonus,memoryIds,question,note};
  }).sort((a,b)=>b.score-a.score||a.destination.visits-b.destination.visits||a.url.localeCompare(b.url));
  if(!ranked.length)throw Error('No approved destination is currently available');const selected=ranked[0],baseline=[...ranked].sort((a,b)=>b.historyScore-a.historyScore||a.destination.visits-b.destination.visits||a.url.localeCompare(b.url))[0];return {selected,baseline,ranked};
 }
 propose(e:Encounter,pageText:string){const {selected,baseline,ranked}=this.rank(e.url,e,pageText),changed=selected.url!==baseline.url,memoryIds=changed?[...new Set([...selected.memoryIds,...baseline.memoryIds])]:selected.question?.memoryIds??[],owner:ResearchProposal['owner']=selected.question?'semantic-assistant':changed?'memory':'supervisor';
  const reason=selected.question?selected.question.reason:changed&&selected.note?`Investigate ${selected.note.title.toLowerCase()} using terms in ${e.label} and its stored encounter. The memory-informed ranking favoured this source.`:selected.destination.from&&canonical(selected.destination.from)===canonical(e.url)?`Inspect a new related page linked from ${e.label}: ${selected.destination.title}.`:selected.destination.visits===0?`Inspect an unvisited ${kind(selected.url)==='coin'?'token detail':kind(selected.url)==='explorer'?'public block record':'source'}: ${selected.destination.title}.`:`Compare ${selected.destination.title} with the earlier encounter after its revisit cooldown.`;
  const p=selected.question??this.journal?.propose(e,selected.url,reason,owner,{memoryIds,sourceIds:selected.note?[selected.note.id]:[]})??{id:'local-choice-'+Date.now(),at:new Date().toISOString(),url:selected.url,reason,owner,status:'proposed' as const,memoryIds,sourceIds:[]};
  this.activeChoice={id:p.id,at:new Date().toISOString(),from:e.url,to:selected.url,objective:reason,owner,memoryIds,baselineUrl:baseline.url,memoryChangedSelection:changed,questionId:p.questionId,scores:ranked.slice(0,12).map(({url,historyScore,memoryBonus,score})=>({url,historyScore,memoryBonus,score}))};this.state.choices.push(this.activeChoice);this.state.choices=this.state.choices.slice(-160);this.save();return p;
 }
 accepted(p:ResearchProposal,e:Encounter,eventId:string){if(p.questionId)this.state.questionVisits[p.questionId]=new Date().toISOString();const choice=this.state.choices.find(c=>c.id===p.id);if(choice?.memoryChangedSelection&&choice.memoryIds.length)this.memory?.destinationUse(e,choice.memoryIds,choice.baselineUrl,choice.to,eventId);this.save();}
 view(){return {version:'persistent-research-v1',updatedAt:this.state.recent.at(-1)?.at,knownDestinations:this.state.destinations.length,revisitCooldownSeconds:180,lastUrl:this.state.lastUrl,recent:this.state.recent,choices:this.state.choices.slice(-20),openQuestions:this.journal?.questions()??[]};}
}
