import type {KnowledgeNote} from '../../shared/memory';
const at='2026-09-12T13:47:00Z';
// Curated notes, not generated narration or a language capability of neurons.
// Short support passages were checked against the linked primary documents.
export const CORPUS:KnowledgeNote[]=[
 {id:'wallets',title:'Wallets and accounts',terms:['wallet','account','connect'],source:'https://ethereum.org/wallets/',retrievedAt:at,support:'A wallet is a tool that lets you interact with your account, using your keys.',note:'Wallet software exposes account balances and tools for signing transactions. Seeing a Connect button does not mean this exhibit has connected a wallet.',creator:'curated-knowledge'},
 {id:'transactions',title:'Transactions',terms:['transaction','trades','buy','sell','gas'],source:'https://ethereum.org/developers/docs/transactions/',retrievedAt:at,support:"a transaction object needs to be signed using the sender's private key",note:'A transaction is an authenticated request that can change chain state. This station observes public pages and cannot sign or submit transactions.',creator:'curated-knowledge'},
 {id:'blocks',title:'Blocks',terms:['block','chain','onchain'],source:'https://ethereum.org/developers/docs/blocks/',retrievedAt:at,support:'Blocks are batches of transactions with a hash of the previous block in the chain.',note:'Blocks organise transactions into linked history. A block explorer provides a view of that history; a webpage alone is not a consensus source.',creator:'curated-knowledge'},
 {id:'contracts',title:'Smart contracts',terms:['contract','pool','address'],source:'https://ethereum.org/developers/docs/smart-contracts/',retrievedAt:at,support:'a program that runs on the Ethereum blockchain',note:'A smart contract has code and state at an address. Reading its address or interface is distinct from invoking a state-changing function.',creator:'curated-knowledge'},
 {id:'tokens',title:'Token interfaces',terms:['token','pons','market','coin'],source:'https://ethereum.org/developers/docs/standards/tokens/erc-20/',retrievedAt:at,support:'ERC-20 Token Standard',note:'ERC-20 specifies a common interface for fungible tokens, including balances and transfers. Names and symbols alone do not establish a token identity.',creator:'curated-knowledge'},
 {id:'explorers',title:'Block explorers',terms:['explorer','blockscout','etherscan','holders'],source:'https://ethereum.org/developers/docs/data-and-analytics/block-explorers/',retrievedAt:at,support:'Block explorers',note:'Explorers expose network data such as blocks, addresses and transactions. Their labels and presentation are separate from the chain records they index.',creator:'curated-knowledge'},
 {id:'annelid',title:'The larval connectome',terms:['platynereis','larva','connectome','neuron','annelid','research'],source:'https://elifesciences.org/articles/97964',retrievedAt:at,support:'Whole-body connectome of a segmented annelid larva',note:'The published reconstruction concerns a three-day-old Platynereis dumerilii larva. Our runtime selects a visual-to-motor subset. Anatomical connectivity alone does not establish its dynamics or a learning rule.',creator:'curated-knowledge'}
];
