import {mkdirSync,readFileSync,existsSync} from 'node:fs';import {writeFile,rename,copyFile,readdir,unlink} from 'node:fs/promises';import {join,resolve} from 'node:path';import {randomUUID,createHash} from 'node:crypto';import {PNG} from 'pngjs';
import type {Circuit} from '../../shared/types';import type {ExhibitDecision} from '../../shared/exhibit';import type {Encounter} from '../../shared/observation';import type {Experience,Recall,MemoryView,AdapterCheckpoint,LearningEvaluation,KnowledgeNote} from '../../shared/memory';import {MODEL_CONFIG} from '../model/config';import {approvedPage} from '../exhibit/external-policy';import {CORPUS} from './corpus';import {checkpoint,learn,retryBudget,adapterContext,ADAPTER,validateCheckpoint} from './adapter';import {projectNotes} from './project-index';
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
const clean=(s:string,max=160)=>s.replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max);
export function canonicalPage(value:string){if(!approvedPage(value)&&!approvedPage(value+'/'))throw new Error('Only approved public encounters may enter memory');const u=new URL(value);u.hash='';u.search='';return u.href.replace(/\/$/,'');}
/** Coarse 8x8 mean-luminance descriptor. Explicit similarity, not identification. */
export function visualDescriptor(bytes:Buffer){const p=PNG.sync.read(bytes),values:number[]=[];for(let gy=0;gy<8;gy++)for(let gx=0;gx<8;gx++){let sum=0,n=0;for(let y=Math.floor(gy*p.height/8);y<Math.floor((gy+1)*p.height/8);y+=4)for(let x=Math.floor(gx*p.width/8);x<Math.floor((gx+1)*p.width/8);x+=4){const i=(y*p.width+x)*4;sum+=(p.data[i]*.2126+p.data[i+1]*.7152+p.data[i+2]*.0722);n++;}values.push(Math.round(sum/Math.max(1,n)/17));}return values;}
export const visualDistance=(a:number[],b:number[])=>a.length===64&&b.length===64?a.reduce((s,n,i)=>s+Math.abs(n-b[i]),0)/64:Infinity;
interface State {version:1;updatedAt:string;experiences:Experience[];recalls:Recall[];adapter:AdapterCheckpoint;evaluation:LearningEvaluation|null}
export class ExperienceStore {
 readonly root:string;private state:State;private writes=Promise.resolve();private ioError?:string;private visual:number[]=[];private encounterFrame?:Buffer;private currentRecall?:Recall;private currentNotes:KnowledgeNote[]=[];private indexedNotes:KnowledgeNote[];
 readonly mode:string;
 constructor(runtime:string,readonly circuit:Circuit,readonly sourceRevision:string,mode=process.env.EXHIBIT_LEARNING_MODE||'train'){
  if(!['train','frozen','disabled'].includes(mode))throw new Error('Unknown learning mode');this.mode=mode;this.indexedNotes=projectNotes(sourceRevision);this.root=resolve(runtime,'memory');mkdirSync(this.root,{recursive:true});
  this.state={version:1,updatedAt:new Date().toISOString(),experiences:[],recalls:[],adapter:checkpoint(),evaluation:null};
  let loaded=false,existing=false;
  for(const name of ['memory.json','memory.previous.json']){try{if(!existsSync(join(this.root,name)))continue;existing=true;const s=JSON.parse(readFileSync(join(this.root,name),'utf8')) as State;if(s.version!==1||s.experiences.length>600||s.recalls.length>1200||s.adapter.version!==ADAPTER.version)throw new Error('Incompatible experience state');validateCheckpoint(s.adapter);for(const e of s.experiences)canonicalPage(e.url);this.state=s;loaded=true;break;}catch(e){this.ioError=`Recovered state unavailable: ${(e as Error).message}`;}}
  if(existing&&!loaded)throw new Error(this.ioError+'; refusing to overwrite existing experience evidence');
  this.state.evaluation=this.evaluation();
 }
 private changed(){
  this.state.updatedAt=new Date().toISOString();this.state.experiences.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));this.state.experiences=this.state.experiences.slice(0,600);this.state.recalls=this.state.recalls.slice(-1200);const bytes=JSON.stringify(this.state),file=join(this.root,'memory.json'),day=this.state.updatedAt.slice(0,10);
  this.writes=this.writes.catch(()=>{}).then(async()=>{await writeFile(file+'.tmp',bytes);if(existsSync(file))await copyFile(file,join(this.root,'memory.previous.json'));await rename(file+'.tmp',file);{const name=`export-${day}.json`;await writeFile(join(this.root,name+'.tmp'),bytes);await rename(join(this.root,name+'.tmp'),join(this.root,name));for(const old of (await readdir(this.root)).filter(n=>/^export-\d{4}-\d{2}-\d{2}\.json$/.test(n)).sort().reverse().slice(7))await unlink(join(this.root,old));}const keep=new Set(this.state.experiences.map(m=>m.id+'.png'));for(const old of (await readdir(this.root)).filter(n=>/^memory-[a-f0-9]{24}\.png$/.test(n)))if(!keep.has(old))await unlink(join(this.root,old));this.ioError=undefined;}).catch(e=>{this.ioError=`Memory persistence failed: ${(e as Error).message}`;});
 }
 async flush(){await this.writes;}
 private notesFor(title:string,url:string,kind:string){const notes=CORPUS.filter(n=>n.terms.some(term=>(title+' '+url+' '+kind).toLowerCase().includes(term))).slice(0,3);return notes.length?notes:CORPUS.filter(n=>kind==='research'?n.id==='annelid':['tokens','contracts'].includes(n.id));}
 private addRecall(r:Recall){this.currentRecall=r;this.state.recalls.push(r);this.changed();return r;}
 encounter(e:Encounter,bytes:Buffer,decision:number){
  const url=canonicalPage(e.url),title=clean(e.label),contentId=hash(title+'|'+(e.tokenAddress??''));this.visual=visualDescriptor(bytes);this.encounterFrame=Buffer.from(bytes);
  const matches=this.state.experiences.flatMap(m=>{const methods:string[]=[],distance=visualDistance(this.visual,m.visual);if(m.url===url)methods.push('canonical-url');if(m.contentId===contentId)methods.push('title-and-address-identity');if(distance<=1)methods.push('coarse-visual-similarity');return methods.length?[{id:m.id,methods,visualDistance:Number.isFinite(distance)?distance:null,score:(methods.includes('canonical-url')?10:0)+(methods.includes('title-and-address-identity')?5:0)+(methods.includes('coarse-visual-similarity')?1:0)}]:[];}).sort((a,b)=>b.score-a.score).slice(0,3).map(({score,...m})=>m);
  this.currentNotes=this.notesFor(title,url,e.kind);
  return this.addRecall({id:'recall-'+randomUUID(),at:new Date().toISOString(),runId:e.runId,decision,reason:'Entered an external visual context; compare prior public encounters. URL and coarse visual matching are reported separately.',matches,retrievedIds:matches.map(m=>m.id),usedIds:[],...(matches.length?{effect:{owner:'knowledge-panel' as const,description:'Prior encounter links are shown as sourced context; no browser control changed.'}}:{})});
 }
 advise(e:Encounter,d:ExhibitDecision){
  const context=adapterContext(e.kind,d.input.encoding,d.command.wheelY),budget=this.mode==='frozen'?retryBudget(this.state.adapter,context):ADAPTER.baseline;
  if(budget===ADAPTER.baseline)return {budget,checkpoint:this.state.adapter.sha256,recallId:this.currentRecall?.id,retrievedIds:this.currentRecall?.retrievedIds??[],usedIds:[] as string[]};
  const ids=(this.state.adapter.cells[context]?.evidenceIds??[]).filter(id=>this.state.experiences.some(m=>m.id===id));
  if(!ids.length)return {budget:ADAPTER.baseline,checkpoint:this.state.adapter.sha256,retrievedIds:[],usedIds:[]};
  const recall=this.addRecall({id:'recall-'+randomUUID(),at:new Date().toISOString(),runId:d.runId,decision:d.decision,reason:'Frozen supervisor adapter retrieved its prior outcome evidence for this engineering context.',matches:ids.map(id=>({id,methods:['page-kind/contrast/direction context'],visualDistance:null})),retrievedIds:ids,usedIds:ids,effect:{owner:'environment-supervisor',description:`Set the unchanged-result retry budget from ${ADAPTER.baseline} to ${budget}. Neural wheel direction is unchanged.`,baseline:ADAPTER.baseline,selected:budget,checkpoint:this.state.adapter.sha256}});
  return {budget,checkpoint:this.state.adapter.sha256,recallId:recall.id,retrievedIds:ids,usedIds:ids};
 }
 observe(e:Encounter,d:ExhibitDecision){
  if(!d.receipt)throw new Error('Memory requires a recorded observed outcome');const url=canonicalPage(e.url),title=clean(e.label),contentId=hash(title+'|'+(e.tokenAddress??'')),id='memory-'+hash(url+'|'+contentId).slice(0,24),at=d.completedAt;
  let m=this.state.experiences.find(x=>x.id===id);if(!m){m={id,createdAt:at,updatedAt:at,url,title,contentId,kind:e.kind,thumbnail:`${d.runId}/${d.imageBefore}`,visual:this.visual.slice(),creator:'experience-store',count:0,visits:[],outcomes:{},displacement:0,contexts:[],evidence:[]};this.state.experiences.push(m);if(this.encounterFrame){const image=Buffer.from(this.encounterFrame);m.thumbnail=`memory/${id}.png`;this.writes=this.writes.then(()=>writeFile(join(this.root,id+'.png'),image));}}
  m.updatedAt=at;m.count++;m.visits=[...new Set([...m.visits,`${d.sessionId}/${e.visitId}`])].slice(-12);m.outcomes[d.receipt.status]=(m.outcomes[d.receipt.status]??0)+1;m.displacement+=Math.abs(d.receipt.scrollAfter-d.receipt.scrollBefore);
  const context=adapterContext(e.kind,d.input.encoding,d.command.wheelY);m.contexts=[...new Set([...m.contexts,context])].slice(-12);
  const link={runId:d.runId,decision:d.decision,commandId:d.commandId,at,frame:`${d.runId}/${d.imageBefore}`,sourceRevision:d.context.sourceRevision,configSha256:d.context.configSha256,input:{left:d.input.left,right:d.input.right,encoding:d.input.encoding},motor:{mean:d.motor.mean,contrast:d.motor.contrast},wheelY:d.command.wheelY,status:d.receipt.status,displacement:d.receipt.scrollAfter-d.receipt.scrollBefore};m.evidence=m.evidence.length>=12?[m.evidence[0],...m.evidence.slice(-10),link]:[...m.evidence,link];
  if(this.mode==='train')this.state.adapter=learn(this.state.adapter,context,d.receipt.status,id);this.changed();return id;
 }
 detail(id:string){const encounter=this.state.experiences.find(m=>m.id===id);return encounter?{encounter,recalls:this.state.recalls.filter(r=>r.retrievedIds.includes(id)),sources:this.notesFor(encounter.title,encounter.url,encounter.kind)}:null;}
 frame(id:string){if(!/^memory-[a-f0-9]{24}$/.test(id)||!this.state.experiences.some(m=>m.id===id))return null;const file=join(this.root,id+'.png');return existsSync(file)?file:null;}
 find(query:{url?:string;title?:string},enabled=true){const url=query.url?canonicalPage(query.url):undefined;if(!enabled)return [];return this.state.experiences.filter(m=>(!url||m.url===url)&&(!query.title||m.title.includes(query.title))).map(m=>({id:m.id,title:m.title,url:m.url,outcomes:m.outcomes,firstObservedAt:m.createdAt,evidence:m.evidence}));}
 adapter(){return structuredClone(this.state.adapter);}
 private evaluation(){try{const result=JSON.parse(readFileSync(join(this.root,'evaluation.json'),'utf8')) as LearningEvaluation;return result.version==='boundary-budget-evaluation-v1'&&result.checkpoint===this.state.adapter.sha256&&result.frozen?result:null;}catch{return null;}}
 view():MemoryView{
  const now=this.state.updatedAt,notes=[...this.currentNotes,...this.indexedNotes,{id:'runtime-profile',title:'Implemented specimen',terms:['specimen'],source:`https://github.com/SpecimenArchive/Specimen-Archive/blob/${this.sourceRevision}/server/model/config.ts`,retrievedAt:now,support:`${this.circuit.nodes.length} implemented cells; ${this.circuit.edges.length} directed connections; ${MODEL_CONFIG.version}`,note:'Configuration and history are indexed directly by software. Retrieving a self-profile is not biological self-awareness.',creator:'configuration-index' as const,revision:this.sourceRevision}];
  return {updatedAt:now,stored:this.state.experiences.length,retrieved:this.state.recalls.filter(r=>r.retrievedIds.length).length,used:this.state.recalls.filter(r=>r.usedIds.length).length,recent:this.state.experiences.slice(0,8),recall:this.currentRecall,notes,selfProfile:{identity:'Specimen 01 / $LARVA / Platynereis dumerilii / 72 hpf',model:MODEL_CONFIG.version,neurons:this.circuit.nodes.length,edges:this.circuit.edges.length,synapses:this.circuit.edges.reduce((n,e)=>n+e.weight,0),capabilities:['Exact native pixel input','Neural wheel direction','Explicit supervisor page selection','Persistent experience retrieval'],limitations:['No language understanding in the larval circuit','No neural coin selection or wallet operations','Engineering dynamics and retry adaptation; no biological learning claim','Native capture requires an unlocked VM console; cold boot currently requires a manual console login',...(this.ioError?[this.ioError]:[])],task:'Observe cryptocurrency, onchain concepts, larval research and implemented circuitry.',sourceRevision:this.sourceRevision,updatedAt:now},learning:{mode:this.mode,checkpoint:this.state.adapter.sha256,trainingEvents:this.state.adapter.trainingEvents,evaluation:this.evaluation()}};
 }
}
