import { test } from 'node:test';
import assert from 'node:assert/strict';
import { PNG } from 'pngjs';
import { readFileSync } from 'node:fs';
import { BrowserController } from '../server/browser/controller';
import { encodeViewport } from '../server/browser/encoder';
import { circuit } from '../scripts/science';
function pixels(targetX:number){const p=new PNG({width:640,height:360});p.data.fill(0);for(let y=184;y<248;y++)for(let x=targetX-44;x<targetX+44;x++){const i=(y*640+x)*4;p.data.set([62,187,105,255],i);}for(let y=210;y<222;y++)for(let x=314;x<326;x++)p.data.set([40,225,250,255],(y*640+x)*4);return PNG.sync.write(p);}
test('actual published circuit turns image changes into opposite decoded movements',async()=>{
  for(const [x,dx] of [[120,-24],[520,24]]){const c=new BrowserController(circuit,'pixel-test','2026-01-01T00:00:00Z','intact'),d=await c.observe(pixels(x),0);assert.equal(d.command.kind,'move');assert.equal(d.command.dx,dx);assert.equal(d.samples.at(-1)!.sensory.left,d.input.left);assert.equal(d.samples.at(-1)!.sensory.right,d.input.right);assert.equal(d.samples.at(-1)!.activity.length,47);}
});
test('activation is generated by computed motors; motor and PRC interventions abolish it',async()=>{
  for(const intervention of ['intact','clamp-all-motors','disconnect-photoreceptors'] as const){const c=new BrowserController(circuit,'intervention-test','2026-01-01T00:00:00Z',intervention),d=await c.observe(pixels(320),0);assert.equal(d.command.kind,intervention==='intact'?'click':'wait');if(intervention!=='intact')assert.equal(d.motor.mean,0);}
});
test('retinal encoding needs observed cursor and target pixels',()=>{
  const png=new PNG({width:640,height:360});png.data.fill(0);const e=encodeViewport(PNG.sync.write(png));assert.equal(e.encoding,'no-signal');assert.equal(e.left,0);assert.equal(e.right,0);
});
test('real Chromium screenshot: antialiased page text cannot shift the cursor centroid',()=>{
  const e=encodeViewport(readFileSync(new URL('./fixtures/browser-retina.png',import.meta.url)));
  assert(Math.abs(e.cursorCentroid!.x-488)<1);assert(Math.abs(e.cursorCentroid!.y-216)<1);assert.equal(e.encoding,'left');
});
