import {mkdirSync,existsSync,readFileSync} from 'node:fs';
import {writeFile,rename,copyFile} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import type {ExhibitDecision} from '../../shared/exhibit';
import type {Encounter} from '../../shared/observation';
import type {JournalEntry,JournalEvidence,JournalKind,ResearchProposal,NarrationContext,NarratorStatus,JournalView} from '../../shared/journal';
const LIMIT=1500;
const emptyEvidence=(e:Encounter):JournalEvidence=>({runId:e.runId,decision:e.decision,commandIds:[],frame:e.thumbnail,memoryIds:[],recallIds:[],sourceIds:[],eventIds:[e.transitionId],url:e.url});
export class LiveJournal {
 readonly root:string;private entries:JournalEntry[]=[];private proposals:ResearchProposal[]=[];private writes=Promise.resolve();private timer?:ReturnType<typeof setTimeout>;private ioError?:string;
 constructor(runtime:string){this.root=resolve(runtime,'journal');mkdirSync(this.root,{recursive:true});let found=false,loaded=false;for(const name of ['journal.json','journal.previous.json']){if(!existsSync(join(this.root,name)))continue;found=true;try{const s=JSON.parse(readFileSync(join(this.root,name),'utf8'));if(s.version!==1||!Array.isArray(s.entries)||s.entries.length>LIMIT||!Array.isArray(s.proposals))throw Error('Invalid journal');this.entries=s.entries;this.proposals=s.proposals;loaded=true;break;}catch{}}if(found&&!loaded)throw Error('Journal evidence is invalid; refusing to replace it');}
 private changed(){if(this.timer)return;this.timer=setTimeout(()=>{this.timer=undefined;this.save();},300);this.timer.unref();}
 private save(){const file=join(this.root,'journal.json'),bytes=JSON.stringify({version:1,entries:this.entries.slice(-LIMIT),proposals:this.proposals.slice(-160)});this.writes=this.writes.catch(()=>{}).then(async()=>{await writeFile(file+'.tmp',bytes);if(existsSync(file))await copyFile(file,join(this.root,'journal.previous.json'));await rename(file+'.tmp',file);this.ioError=undefined;}).catch(()=>{this.ioError='Journal persistence is unavailable; recent entries may not survive a restart.';});}
 async flush(){clearTimeout(this.timer);this.timer=undefined;this.save();await this.writes;}
 add(entry:Omit<JournalEntry,'id'|'at'|'updatedAt'|'count'> & {at?:string}){const at=entry.at??new Date().toISOString(),result:JournalEntry={...entry,id:'journal-'+randomUUID(),at,updatedAt:at,count:1};this.entries.push(result);this.entries=this.entries.slice(-LIMIT);this.changed();return result;}
 entered(e:Encounter,reason:string,proposal?:ResearchProposal){return this.add({kind:'OBSERVE',owner:'structured-events',text:`Opened ${e.label}. ${reason}`,topic:e.label,visitId:e.visitId,status:'observed',evidence:emptyEvidence(e),proposalId:proposal?.id});}
 recall(e:Encounter,context:NarrationContext){if(!context.memories.length)return;const identity=context.memories.some(m=>m.method.includes('canonical-url')||m.method.includes('title-and-address'));this.add({kind:'RECALL',owner:'structured-events',text:identity?`This page connects to a recorded encounter: ${context.memories[0].title}.`:`A coarse image comparison retrieved ${context.memories.length} prior encounter${context.memories.length===1?'':'s'} for inspection; identity is unconfirmed.`,topic:e.label,visitId:e.visitId,status:'observed',evidence:{...emptyEvidence(e),frame:context.frame,memoryIds:context.memories.map(m=>m.id),recallIds:context.recallIds},context});}
 outcome(e:Encounter,d:ExhibitDecision){const r=d.receipt;if(!r)return;const kind:JournalKind=r.status==='moved'?'ACT':'RESULT',status=r.status==='moved'?'verified':r.status==='wait'?'wait':r.status==='boundary'?'boundary':'failed',prior=this.entries.at(-1),evidence:JournalEvidence={...emptyEvidence(e),runId:d.runId,decision:d.decision,commandIds:[d.commandId],frame:`${d.runId}/${d.imageBefore}`,memoryIds:d.memory?.retrievedIds??[],recallIds:d.memory?.recallId?[d.memory.recallId]:[],modelStep:d.modelEndStep};
  if(prior&&prior.visitId===e.visitId&&prior.kind===kind&&prior.status===status&&prior.count<12&&Date.parse(d.completedAt)-Date.parse(prior.at)<45000){prior.count++;prior.updatedAt=d.completedAt;prior.evidence.commandIds.push(d.commandId);prior.evidence.memoryIds=[...new Set([...prior.evidence.memoryIds,...evidence.memoryIds])];prior.evidence.recallIds=[...new Set([...prior.evidence.recallIds,...evidence.recallIds])];prior.text=status==='verified'?`${prior.count} neural wheel commands produced verified page movement.`:status==='boundary'?`${prior.count} acknowledged wheel commands reached a scroll boundary.`:status==='wait'?`The motor gate stayed closed for ${prior.count} recorded windows.`:`${prior.count} actions were held or failed verification. ${r.reason}`;this.changed();return prior;}
  return this.add({kind,owner:'structured-events',text:status==='verified'?`Neural wheel input moved the visible page ${Math.abs(r.scrollAfter-r.scrollBefore)} px ${r.scrollAfter>r.scrollBefore?'down':'up'}.`:status==='wait'?'The circuit is active; its motor output did not open the action gate.':status==='boundary'?'The wheel event was acknowledged; the page stayed at its scroll boundary.':`Input was held or failed verification. ${r.reason}`,topic:e.label,visitId:e.visitId,status,evidence,at:d.completedAt});
 }
 propose(e:Encounter,url:string,reason:string,owner:ResearchProposal['owner'],support:{questionId?:string;memoryIds?:string[];sourceIds?:string[]}={}){const p:ResearchProposal={id:'proposal-'+randomUUID(),at:new Date().toISOString(),url,reason,owner,status:'proposed',memoryIds:support.memoryIds??[],sourceIds:support.sourceIds??[],questionId:support.questionId};this.proposals.push(p);this.proposals=this.proposals.slice(-160);this.add({kind:'NEXT',owner:owner==='semantic-assistant'?'semantic-narrator':'supervisor',text:reason,topic:e.label,visitId:e.visitId,status:'proposed',proposalId:p.id,evidence:{...emptyEvidence(e),destination:url,memoryIds:p.memoryIds,sourceIds:p.sourceIds}});return p;}
 questions(){return this.entries.filter(e=>e.kind==='QUESTION').slice(-12).map(e=>({id:e.id,text:e.text,url:e.evidence.url,at:e.at}));}
 pending(){return this.proposals.filter(p=>p.status==='proposed'&&p.owner==='semantic-assistant'&&Date.now()-Date.parse(p.at)<600000);}
 transition(p:ResearchProposal,status:'accepted'|'completed'|'failed',e:Encounter,eventId?:string){p.status=status;p.eventId=eventId;this.add({kind:status==='accepted'?'NEXT':'RESULT',owner:'supervisor',text:status==='accepted'?`Supervisor accepted: ${p.reason}`:status==='completed'?`Research transition verified: ${e.label}.`:'The proposed destination could not be verified; supervisor recovery follows.',topic:e.label,visitId:e.visitId,status:status==='completed'?'verified':status,evidence:{...emptyEvidence(e),destination:p.url,memoryIds:p.memoryIds,sourceIds:p.sourceIds,eventIds:eventId?[eventId]:[]},proposalId:p.id});this.changed();}
 detail(id:string){return this.entries.find(e=>e.id===id)??null;}
 view(narrator:NarratorStatus,options:{before?:string;limit?:number;kind?:string}={}):JournalView{const selected=this.entries.filter(e=>(!options.before||e.at<options.before)&&(!options.kind||e.kind===options.kind));return {updatedAt:this.entries.at(-1)?.updatedAt??new Date().toISOString(),entries:selected.slice(-Math.min(options.limit??80,200)).map(({context,...e})=>e),proposals:this.proposals.slice(-30),narrator:{...narrator,...(this.ioError?{message:this.ioError}:{} )},retention:LIMIT,total:this.entries.length};}
}
