// Fixture setup and evaluation are owned by the harness. This file is never
// imported by the retinal encoder, neural controller or motor decoder.
export function targetForSeed(seed:number){const v=(Math.imul(seed,1664525)+1013904223)>>>0;return 110+(v%421);}
export function taskHTML(seed:number){const x=targetForSeed(seed);
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Specimen browser experiment</title>
<style>*{box-sizing:border-box}body{margin:0;background:#131c20;color:#d9e4e0;font:14px system-ui;overflow:hidden;cursor:none}header{padding:24px 28px;border-bottom:1px solid #2a363b}small{display:block;color:#9bacae;font:10px monospace;letter-spacing:2px;margin-bottom:9px}h1{font-size:19px;font-weight:500;margin:0}.lane{position:absolute;left:28px;right:28px;top:216px;border-top:1px dashed #415257}button{position:absolute;left:${x-44}px;top:184px;width:88px;height:64px;border:0;border-radius:8px;background:rgb(62,187,105);color:#0b2516;font:600 12px system-ui;cursor:none}button.done{background:#686d81;color:white}#cursor{position:absolute;left:320px;top:216px;width:18px;height:18px;border:3px solid rgb(40,225,250);border-radius:50%;transform:translate(-50%,-50%);pointer-events:none}footer{position:absolute;bottom:24px;left:28px;color:#aeb9be;font:11px monospace}#result{position:absolute;top:115px;left:28px;font-size:14px;color:#bfcace}</style>
<header><small>SPECIMEN ARCHIVE / CONTROLLED BROWSER TASK</small><h1>Acquire the visible button</h1></header><div id="result">Awaiting activation</div><div class="lane"></div><button id="target">ACTIVATE</button><div id="cursor"></div><footer>640 × 360 px · horizontal lane · input from captured pixels</footer>
<script>window.__events=[];window.__outcome={activated:false,activationCount:0};for(const type of ['mousemove','mousedown','mouseup','click'])addEventListener(type,e=>{if(type==='mousemove'){const c=document.getElementById('cursor');c.style.left=e.clientX+'px';c.style.top=e.clientY+'px'}window.__events.push({type,x:e.clientX,y:e.clientY,button:e.button,trusted:e.isTrusted,pageTimeMs:performance.now(),timestamp:new Date().toISOString()})});document.getElementById('target').addEventListener('click',function(){window.__outcome.activated=true;window.__outcome.activationCount++;this.className='done';this.textContent='ACTIVATED';document.getElementById('result').textContent='Page changed by a real button click'});</script></html>`;
}
