import type {Encounter} from './observation';
export type JournalKind='OBSERVE'|'RECALL'|'CONNECT'|'QUESTION'|'NEXT'|'ACT'|'RESULT';
export interface JournalEvidence {runId:string;decision?:number;commandIds:string[];frame?:string;memoryIds:string[];recallIds:string[];sourceIds:string[];eventIds:string[];url:string;destination?:string;modelStep?:number}
export interface ResearchProposal {id:string;at:string;url:string;reason:string;owner:'supervisor'|'semantic-assistant'|'memory';status:'proposed'|'accepted'|'completed'|'failed'|'superseded';questionId?:string;memoryIds:string[];sourceIds:string[];eventId?:string}
export interface JournalEntry {id:string;at:string;updatedAt:string;kind:JournalKind;owner:'structured-events'|'semantic-narrator'|'supervisor';text:string;topic:string;visitId:string;status:'observed'|'interpretation'|'question'|'proposed'|'accepted'|'verified'|'failed'|'wait'|'boundary';count:number;evidence:JournalEvidence;proposalId?:string;provider?:string;model?:string;context?:NarrationContext}
export interface NarrationContext {encounter:Encounter;capturedAt:string;frame:string;pageText:string;pageTextSha256:string;memories:{id:string;title:string;url:string;method:string;outcomes:Record<string,number>}[];recallIds:string[];sources:{id:string;title:string;url:string;passage:string}[];candidates:{id:string;url:string;title:string}[];openQuestions?:{id:string;text:string;url:string;at:string}[];lastOutcome?:{status:string;reason:string;commandId:string};model:{neurons:number;mean:number;contrast:number}}
export interface NarratorDraft {id:string;at:string;topic:string;visitId:string;url:string;texts:string[]}
export interface NarratorStatus {configured:boolean;state:'unconfigured'|'ready'|'generating'|'unavailable'|'limited';provider?:string;model?:string;lastSuccess?:string;message:string;pending:number;requestsThisHour:number;maximumRequestsPerHour:number;nextRequestAt?:string;skippedDuplicates?:number;minimumIntervalSeconds?:number}
export interface JournalView {updatedAt:string;entries:JournalEntry[];proposals:ResearchProposal[];narrator:NarratorStatus;retention:number;total:number}
