import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {resolve,join} from 'node:path';import assert from 'node:assert/strict';import {gzipSync} from 'node:zlib';import type {Circuit} from '../shared/types';import {ExhibitController} from '../server/exhibit/controller';import {OBSERVATION_RETINA} from '../server/exhibit/observation-encoder';import {sha256} from '../server/browser/evidence';import {executionOrigin} from '../server/provenance';
const root=resolve(process.argv[2]||'runtime/pons'),out=resolve(process.argv[3]||'runtime/pons/ablation');mkdirSync(out,{recursive:true});const manifest=JSON.parse(readFileSync(join(root,'holdout-manifest.json'),'utf8')),circuit=JSON.parse(readFileSync('data/processed/circuit.json','utf8')) as Circuit;
const seeds=[503,607,809],interventions=['intact','disconnect-photoreceptors','clamp-all-motors'] as const,results:any[]=[];
for(const seed of seeds){let random=seed>>>0;const order=[...manifest.cases];for(let i=order.length-1;i>0;i--){random=(Math.imul(random,1664525)+1013904223)>>>0;const j=random%(i+1);[order[i],order[j]]=[order[j],order[i]];}
 for(const intervention of interventions){const id=`external-control-${seed}-${intervention}`,at=new Date().toISOString(),controller=new ExhibitController(circuit,id,at,intervention),replay=new ExhibitController(circuit,id,at,intervention),rows=[];
  for(const [decision,c] of order.entries()){const png=readFileSync(join(root,c.file)),d=await controller.observe(png,decision,undefined,OBSERVATION_RETINA.version),again=await replay.observe(png,decision,undefined,OBSERVATION_RETINA.version);assert.deepEqual(d.command,again.command);assert.deepEqual(d.samples.map(s=>[s.activity,s.pose,s.sensory,s.seq]),again.samples.map(s=>[s.activity,s.pose,s.sensory,s.seq]));rows.push({file:c.file,url:c.url,capturedAt:c.at,sha256:sha256(png),...d});}
  writeFileSync(join(out,id+'.json.gz'),gzipSync(JSON.stringify(rows)));results.push({seed,intervention,decisions:rows.length,neuralSamples:rows.reduce((n,d)=>n+d.samples.length,0),commands:rows.map(d=>({file:d.file,kind:d.command.kind,wheelY:d.command.wheelY,input:d.input,motor:d.motor})),exactReplay:true,artifact:id+'.json.gz'});
 }
}
const report={at:new Date().toISOString(),origin:executionOrigin('external-held-out-ablation'),method:'Five actual VM-captured held-out public pages; three seeded page orders; identical intact/disconnected/clamped budgets; fixed retina/rate model/decoder. This check covers pixel-to-proposal causality; browser dispatch is verified separately in the live native trace.',profile:OBSERVATION_RETINA.version,seeds,results};writeFileSync(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(results.map(r=>({seed:r.seed,intervention:r.intervention,decisions:r.decisions,scrolls:r.commands.filter((d:any)=>d.kind==='scroll').length,up:r.commands.filter((d:any)=>d.wheelY<0).length,down:r.commands.filter((d:any)=>d.wheelY>0).length,exactReplay:r.exactReplay}))));
