// Record actual streaming commentary and paired observation views. No playback,
// injected journal entries, camera movement or browser-controller actions.
import {chromium} from '@playwright/test';import fs from 'node:fs';import assert from 'node:assert/strict';
const base=process.env.SPECIMEN_REVIEW_URL??'https://specimenarchive.com',root='runtime/laboratory/recording-'+Date.now();fs.mkdirSync(root,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1920,height:1200},recordVideo:{dir:root,size:{width:1920,height:1200}}});
await context.addInitScript(()=>{window.__draftUpdates=[];const Original=window.EventSource;window.EventSource=class extends Original{constructor(...args){super(...args);this.addEventListener('message',event=>{try{const {draft}=JSON.parse(event.data);window.__draftUpdates.push({at:new Date().toISOString(),id:draft?.id??null,texts:draft?.texts??[]});}catch{}});}};});
const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));let result={},video;
try{await page.goto(base);video=page.video();await page.waitForFunction(()=>document.querySelector('.direct-desktop')?.getAttribute('data-desktop-frame'),null,{timeout:90000});const observationReadyAt=new Date().toISOString(),start=await(await fetch(base+'/api/exhibit/live')).json();console.log(JSON.stringify({ready:true,root,source:start.sourceRevision}));
 await page.waitForFunction(()=>document.querySelector('.journal-draft p')?.textContent.length>20,null,{timeout:180000});const draftAt=new Date().toISOString();await page.screenshot({path:root+'/streaming.png'});console.log(JSON.stringify({streaming:true,draftAt}));let acceptedAt;const deadline=Date.now()+240000;while(Date.now()<deadline){const state=await(await fetch(base+'/api/journal')).json();if(Date.parse(state.narrator.lastSuccess??'')>=Date.parse(draftAt)){acceptedAt=state.narrator.lastSuccess;break;}await page.waitForTimeout(4000);}assert(acceptedAt,'No supported commentary completed during the recording window');await page.screenshot({path:root+'/accepted.png'});console.log(JSON.stringify({accepted:true,acceptedAt}));await page.waitForTimeout(45000);await page.screenshot({path:root+'/observe.png'});const end=await(await fetch(base+'/api/exhibit/live')).json(),journal=await(await fetch(base+'/api/journal')).json(),updates=await page.evaluate(()=>window.__draftUpdates);assert.equal(start.sourceRevision,end.sourceRevision);assert.equal(errors.length,0);result={observationReadyAt,acceptedAt,endedAt:new Date().toISOString(),draftAt,observerAssets:await page.evaluate(()=>[...document.scripts].map(s=>s.src).filter(Boolean)),sourceRevision:start.sourceRevision,sourceDirty:start.sourceDirty,sessionId:start.sessionId,startRun:start.runId,endRun:end.runId,width:1920,height:1200,updates,journal,errors};
}catch(e){result={...result,error:e.message,errors};process.exitCode=1;console.error(e.message);}finally{await context.close();if(video){await video.saveAs(root+'/raw.webm');await video.delete();}fs.writeFileSync(root+'/capture.json',JSON.stringify(result,null,2));await browser.close();console.log(JSON.stringify({saved:root,error:result.error??null}));}
