import {chromium} from '@playwright/test';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve,join} from 'node:path';import {gzipSync} from 'node:zlib';import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';import type {Circuit} from '../shared/types';import type {AdapterCheckpoint,LearningEvaluation} from '../shared/memory';
import {ExhibitController} from '../server/exhibit/controller';import {OBSERVATION_RETINA} from '../server/exhibit/observation-encoder';import {retryBudget,adapterContext,validateCheckpoint} from '../server/memory/adapter';import {executionOrigin} from '../server/provenance';
const input=resolve(process.argv[2]||'runtime/pons'),frozen=resolve(process.argv[3]||'runtime/memory/frozen-checkpoint.json'),output=resolve(process.argv[4]||'runtime/memory-evaluation');mkdirSync(output,{recursive:true});
const state=validateCheckpoint(JSON.parse(readFileSync(frozen,'utf8')) as AdapterCheckpoint),manifest=JSON.parse(readFileSync(join(input,'holdout-manifest.json'),'utf8')),circuit=JSON.parse(readFileSync('data/processed/circuit.json','utf8')) as Circuit,seeds=[503,607,809],arms=['baseline','adaptation','disabled'] as const;
const original=JSON.stringify(state),hash=(b:Buffer|string)=>createHash('sha256').update(b).digest('hex'),cases=manifest.cases.map((c:any)=>({...c,bytes:readFileSync(join(input,c.file))}));
// Controlled browser integration, explicitly not a live Pons trial. Original
// held-out images are scrollable in a shorter viewport; no response is invented.
const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||(process.platform==='win32'?'chrome':undefined)}),rows:any[]=[];
try{for(const seed of seeds){let random=seed>>>0;const order=cases.map((_:any,i:number)=>i);for(let i=order.length-1;i>0;i--){random=(Math.imul(random,1664525)+1013904223)>>>0;const j=random%(i+1);[order[i],order[j]]=[order[j],order[i]];}
 for(const arm of arms){const context=await browser.newContext({viewport:{width:1280,height:360},acceptDownloads:false,serviceWorkers:'block'});let active=cases[0],events:any[]=[];
 await context.route('**/*',route=>route.request().url()==='https://memory-evaluation.invalid/'?route.fulfill({contentType:'text/html',body:`<!doctype html><style>html,body{margin:0;background:white}img{display:block;width:1280px;max-width:none}</style><img src="data:image/png;base64,${active.bytes.toString('base64')}" alt="Recorded held-out input; controlled integration fixture">`}):route.abort());
 await context.exposeBinding('__wheel',(_,e)=>events.push(e));await context.addInitScript(()=>addEventListener('wheel',e=>void(window as any).__wheel({trusted:e.isTrusted,deltaY:e.deltaY,x:e.clientX,y:e.clientY}),true));
 const page=await context.newPage(),id=`retry-${seed}-${arm}`,startedAt=new Date().toISOString(),controller=new ExhibitController(circuit,id,startedAt),replay=new ExhibitController(circuit,id,startedAt),traces:any[]=[];
 let visit=-1,windows=0,unchanged=0,budget=3,transitions=0;const totals={attempts:0,moved:0,boundary:0,displacement:0,windows:48};
 try{for(let decision=0;decision<48;decision++){
  if(visit<0||windows>=8||unchanged>=budget){visit++;active=cases[order[visit%order.length]];await page.goto('https://memory-evaluation.invalid/',{waitUntil:'load'});await page.locator('img').evaluate((i:any)=>i.decode());const starting=['top','middle','bottom'][seeds.indexOf(seed)];await page.evaluate(where=>{const r=document.scrollingElement!;r.scrollTop=where==='top'?0:where==='middle'?(r.scrollHeight-r.clientHeight)/2:r.scrollHeight;},starting);await page.mouse.move(512,252);await page.waitForTimeout(100);windows=0;unchanged=0;budget=3;transitions++;}
  const png=await page.screenshot(),calculation=await controller.observe(png,decision,undefined,OBSERVATION_RETINA.version),again=await replay.observe(png,decision,undefined,OBSERVATION_RETINA.version);assert.deepEqual(calculation.command,again.command);assert.deepEqual(calculation.samples.map(s=>[s.activity,s.pose,s.sensory,s.seq]),again.samples.map(s=>[s.activity,s.pose,s.sensory,s.seq]));
  const before=await page.evaluate(()=>document.scrollingElement!.scrollTop);events=[];
  if(calculation.command.kind==='scroll'){await page.mouse.wheel(0,calculation.command.wheelY);await page.waitForTimeout(100);assert.equal(events.length,1);assert.equal(events[0].trusted,true);assert.equal(events[0].deltaY,calculation.command.wheelY);totals.attempts++;}
  const after=await page.evaluate(()=>document.scrollingElement!.scrollTop),delta=after-before,status=calculation.command.kind!=='scroll'?'wait':delta?'moved':'boundary';
  if(status==='moved'){totals.moved++;totals.displacement+=Math.abs(delta);}if(status==='boundary')totals.boundary++;
  assert(delta*calculation.command.wheelY>=0);assert(Math.abs(delta)<=Math.abs(calculation.command.wheelY)+1);unchanged=status==='moved'?0:unchanged+1;windows++;
  const kind=active.url.includes('elifesciences')?'research':active.url.split('/').at(-1)==='launchpad'?'explore':'coin',key=adapterContext(kind,calculation.input.encoding,calculation.command.wheelY);budget=arm==='adaptation'?retryBudget(state,key):3;
  const file=`${id}-${decision}.png`;writeFileSync(join(output,file),png);traces.push({file,sha256:hash(png),originalFile:active.file,originalSha256:hash(active.bytes),kind,context:key,selectedRetryBudget:budget,visit,before,after,status,events:[...events],...calculation});
 }
 const artifact=id+'.json.gz',bytes=gzipSync(JSON.stringify(traces));writeFileSync(join(output,artifact),bytes);rows.push({seed,arm,startedAt,completedAt:new Date().toISOString(),...totals,transitions,exactReplay:true,artifact,sha256:hash(bytes),budgets:[...new Set(traces.map(d=>d.selectedRetryBudget))]});console.log(JSON.stringify(rows.at(-1)));
 }catch(e){rows.push({seed,arm,error:(e as Error).message,...totals,completedWindows:traces.length});writeFileSync(join(output,id+'-failed.json.gz'),gzipSync(JSON.stringify(traces)));throw e;}finally{await context.close();}
 }
}}finally{await browser.close();writeFileSync(join(output,'trials.json'),JSON.stringify(rows,null,2));}
assert.equal(JSON.stringify(state),original,'Evaluation cannot train the frozen checkpoint');
const total=(arm:string)=>{const a={attempts:0,moved:0,boundary:0,displacement:0,windows:0};for(const r of rows.filter(r=>r.arm===arm))for(const k of Object.keys(a) as (keyof typeof a)[])a[k]+=r[k];return a;};
const baseline=total('baseline'),adaptation=total('adaptation'),disabled=total('disabled');assert.deepEqual(baseline,disabled);
const unchanged=JSON.stringify(baseline)===JSON.stringify(adaptation),evaluation:LearningEvaluation={version:'boundary-budget-evaluation-v1',at:new Date().toISOString(),checkpoint:state.sha256,method:'Controlled Chrome scrolling of five actual pre-training VM screenshots in a 1280 × 360 viewport, not live Pons. Seeds fix identical page orders and top/middle/bottom starting offsets. 48 windows per arm/seed; eight-window encounter ceiling; pixel-only network and actual trusted wheel dispatch.',frozen:true,baseline,adaptation,disabled,seeds,result:unchanged?'No measured improvement: all three arms produced identical aggregate outcomes.':`Frozen adaptation: ${adaptation.moved}/${adaptation.attempts} visible moves versus ${baseline.moved}/${baseline.attempts} baseline; ${adaptation.displacement}/${adaptation.windows} versus ${baseline.displacement}/${baseline.windows} displaced pixels per window.`,limitations:['This controlled recorded-image integration benchmark does not establish improvement on live Pons.','The learned component is a software retry budget, not neural plasticity.','No tuning on held-out outcomes; all trials and exact neural traces are retained.'],sourceRevision:executionOrigin('memory-evaluation').sourceRevision,evidence:'https://github.com/SpecimenArchive/Specimen-Archive/blob/master/docs/results/memory-evaluation.json'};
writeFileSync(join(output,'evaluation.json'),JSON.stringify(evaluation,null,2));console.log(JSON.stringify(evaluation));
