import {readFileSync,writeFileSync,readdirSync,existsSync,copyFileSync,renameSync} from 'node:fs';import {join,resolve} from 'node:path';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
import {canonicalPage,visualDescriptor} from '../server/memory/store';import {validateCheckpoint,adapterContext} from '../server/memory/adapter';import type {Experience,Recall} from '../shared/memory';import type {ExhibitRecord} from '../shared/exhibit';
const runtime=resolve(process.argv[2]||'runtime'),root=join(runtime,'memory'),at=new Date().toISOString(),frozen=validateCheckpoint(JSON.parse(readFileSync(join(root,'frozen-checkpoint.json'),'utf8'))),receipt=JSON.parse(readFileSync(join(root,'freeze-receipt.json'),'utf8'));
try{const response=await fetch('http://127.0.0.1:4317/api/health',{signal:AbortSignal.timeout(1500)});if(response.ok)throw new Error('Stop the backend gracefully before restoring memory.');}catch(e){if((e as Error).message.startsWith('Stop the backend'))throw e;}
const prior=JSON.parse(readFileSync(join(root,'memory.json'),'utf8')),records=readdirSync(join(runtime,'exhibit-publications/experiments')).filter(n=>n.endsWith('.record.json')).map(n=>JSON.parse(readFileSync(join(runtime,'exhibit-publications/experiments',n),'utf8')) as ExhibitRecord).filter(r=>r.memoryConfig).sort((a,b)=>a.startedAt.localeCompare(b.startedAt)),map=new Map<string,Experience>(),recalls=new Map<string,Recall>((prior.recalls as Recall[]).map(r=>[r.id,r]));
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');let training=0,links=0,thumbnails=0;const restoredFrom=new Set<string>();
for(const r of records)for(const d of r.decisions){if(!d.memory?.storedId||!d.page||!d.receipt)continue;const url=canonicalPage(d.page.url),title=d.page.label,token=url.match(/\/launchpad\/(0x[a-fA-F0-9]{40})$/)?.[1]??'',kind=token?'coin':url.endsWith('/launchpad')?'explore':'research',contentId=hash(title+'|'+token),id='memory-'+hash(url+'|'+contentId).slice(0,24);assert.equal(id,d.memory.storedId);
let m=map.get(id);if(!m){m={id,createdAt:d.completedAt,updatedAt:d.completedAt,url,title,contentId,kind,thumbnail:'',visual:[],creator:'experience-store',count:0,visits:[],outcomes:{},displacement:0,contexts:[],evidence:[]};map.set(id,m);}
if(!m.thumbnail){const file=join(runtime,'exhibit',d.runId,d.imageBefore);if(existsSync(file)){const bytes=readFileSync(file);m.visual=visualDescriptor(bytes);m.thumbnail=`memory/${id}.png`;copyFileSync(file,join(root,id+'.png'));thumbnails++;}}
m.updatedAt=d.completedAt;m.count++;m.visits=[...new Set([...m.visits,'recovered-record/'+d.runId])].slice(-12);m.outcomes[d.receipt.status]=(m.outcomes[d.receipt.status]??0)+1;m.displacement+=Math.abs(d.receipt.scrollAfter-d.receipt.scrollBefore);m.contexts=[...new Set([...m.contexts,adapterContext(kind,d.input.encoding,d.command.wheelY)])].slice(-12);
const link={runId:d.runId,decision:d.decision,commandId:d.commandId,at:d.completedAt,frame:`${d.runId}/${d.imageBefore}`,sourceRevision:d.context.sourceRevision,configSha256:d.context.configSha256,input:{left:d.input.left,right:d.input.right,encoding:d.input.encoding},motor:{mean:d.motor.mean,contrast:d.motor.contrast},wheelY:d.command.wheelY,status:d.receipt.status,displacement:d.receipt.scrollAfter-d.receipt.scrollBefore};m.evidence=m.evidence.length>=12?[m.evidence[0],...m.evidence.slice(-10),link]:[...m.evidence,link];links++;restoredFrom.add(r.id);
if(r.memoryConfig?.mode==='train'&&['moved','boundary'].includes(d.receipt.status))training++;
if(d.memory.recallId&&!recalls.has(d.memory.recallId))recalls.set(d.memory.recallId,{id:d.memory.recallId,at:d.completedAt,runId:d.runId,decision:d.decision,reason:'Recovered linkage from an immutable decision completed at this timestamp. Original recall timing and matcher diagnostics were not retained; no recognition method is inferred.',retrievedIds:d.memory.retrievedIds,usedIds:d.memory.usedIds,matches:d.memory.retrievedIds.map(id=>({id,methods:['recovered decision linkage; original matcher unavailable'],visualDistance:null}))});
}
assert.equal(training,frozen.trainingEvents,'All actual training outcomes must be recoverable');for(const id of receipt.ids)assert(map.has(id),'Missing original trained encounter: '+id);
const state={version:1,updatedAt:at,experiences:[...map.values()].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),recalls:[...recalls.values()].sort((a,b)=>a.at.localeCompare(b.at)).slice(-1200),adapter:frozen,evaluation:null,recovery:{at,reason:'Canonical trailing-slash validation rejected a stored atlas URL; rebuilt the index from immutable decision records.',trainingOutcomes:training,decisionLinks:links,originalMemoryIdsPreserved:receipt.ids.length,restoredFrom:[...restoredFrom],limitations:['Original per-visit IDs and some recall matcher diagnostics were not retained; reconstructed links explicitly identify that limitation.','Thumbnails use an available original captured decision from the same encounter; no image is fabricated.']}};
const backup=join(root,'pre-recovery-'+Date.now()+'.json');copyFileSync(join(root,'memory.json'),backup);writeFileSync(join(root,'memory.json.tmp'),JSON.stringify(state));renameSync(join(root,'memory.json.tmp'),join(root,'memory.json'));copyFileSync(join(root,'memory.json'),join(root,'memory.previous.json'));writeFileSync(join(root,'recovery-receipt.json'),JSON.stringify(state.recovery,null,2));console.log(JSON.stringify({...state.recovery,stored:state.experiences.length,thumbnails,checkpoint:frozen.sha256}));
