// Read-only public observer review. Endurance can invoke the separately supplied,
// operator-owned worker restart script; it never drives the observed browser.
import {chromium} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
const endurance=process.argv.includes('--endurance'),restartWorker=!process.argv.includes('--no-worker-restart'),base=process.env.SPECIMEN_REVIEW_URL??'https://specimenarchive.com';
const root=`runtime/showcase/${endurance?'endurance':'review'}-${Date.now()}`;mkdirSync(root,{recursive:true});
const errors=[],samples=[],layouts=[],choices=new Map(),visits=new Map(),entries=new Map();let result={},restart,initial,matching=0,lastPacket=0,paired=0,offline=false,freeze=false,recovered=false;
const browser=await chromium.launch({headless:true,channel:'msedge'});
async function json(path){const r=await fetch(base+path,{signal:AbortSignal.timeout(15000)});assert(r.ok,`${path}: ${r.status}`);return r.json();}
async function observer(record=false){const context=await browser.newContext({viewport:{width:1920,height:1080},...(record?{recordVideo:{dir:root,size:{width:1920,height:1080}}}:{})});await context.addInitScript(()=>{window.__packets=[];window.__sockets=[];const Base=window.WebSocket;window.WebSocket=class extends Base{constructor(...args){super(...args);window.__sockets.push(this);this.addEventListener('message',e=>{const p=JSON.parse(e.data).exhibit;if(p){window.__packets.push({n:p.packetSeq,session:p.sessionId,run:p.runId,signature:JSON.stringify([p.snapshot?.seq,p.snapshot?.activity,p.display?.path,p.commandId])});if(window.__packets.length>500)window.__packets.shift();}});}};});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForFunction(()=>document.querySelector('.direct-desktop')?.getAttribute('data-desktop-frame'),null,{timeout:60000});return {context,page};}
function workerRestart(){const file=process.env.SPECIMEN_RESTART_SCRIPT;assert(file,'Endurance requires an explicit private worker restart script');return new Promise((resolve,reject)=>{const child=spawn(process.execPath,['scripts/windows/private-vm-access.mjs','run',file],{windowsHide:true,stdio:['ignore','pipe','pipe']});let output='';child.stdout.on('data',x=>output+=x);child.stderr.on('data',x=>output+=x);child.on('error',reject);child.on('exit',code=>code===0?resolve({completedAt:new Date().toISOString(),output}):reject(Error('Worker restart failed: '+output)));});}
async function pairedViews(page){const m=await page.evaluate(()=>{const one=s=>document.querySelector(s),stage=one('.observation-stage'),session=one('.session-line');return {health:one('.exhibit-status')?.textContent,frames:[...stage.children].slice(0,2).map(c=>c.getAttribute('data-desktop-frame')),steps:[session,one('.specimen-panel'),one('.signal-panel')].map(c=>c?.getAttribute('data-model-step')),runs:[session,one('.specimen-panel'),one('.signal-panel')].map(c=>c?.getAttribute('data-run-id'))};});assert.equal(m.frames[0],m.frames[1]);assert.equal(new Set(m.steps).size,1);assert.equal(new Set(m.runs).size,1);paired++;return m;}
async function collect(seconds){const [health,planner,journal]=await Promise.all([json('/api/health'),json('/api/exploration'),json('/api/journal')]);assert.equal(health.sessionId,initial.sessionId);planner.choices.forEach(c=>choices.set(c.id,c));planner.recent.forEach(v=>visits.set(v.visitId,v));journal.entries.forEach(e=>entries.set(e.id,e));samples.push({seconds,at:new Date().toISOString(),health,narrator:journal.narrator,lastUrl:planner.lastUrl,known:planner.knownDestinations});return {health,planner,journal};}
let a,b;
try{
 a=await observer(!endurance);if(endurance)b=await observer();initial=await json('/api/health');if(!endurance)await a.page.locator('.session-line').evaluate(e=>e.scrollIntoView({block:'start'}));const live=await json('/api/exhibit/live'),started=Date.now(),video=a.page.video();
 console.log(JSON.stringify({ready:true,root,session:initial.sessionId,source:live.sourceRevision}));
 const duration=endurance?601000:55000;
 while(Date.now()-started<duration){const seconds=(Date.now()-started)/1000;const state=await collect(seconds);samples.at(-1).presentation=await pairedViews(a.page);
  if(endurance){const [aa,bb]=await Promise.all([a.page,b.page].map(p=>p.evaluate(()=>window.__packets))),map=new Map(bb.map(p=>[p.n,p]));for(const p of aa){const q=map.get(p.n);if(p.n>lastPacket&&q){assert.equal(p.signature,q.signature);assert.equal(p.session,q.session);matching++;lastPacket=p.n;}}
   if(seconds>130&&!offline){await b.context.setOffline(true);await b.page.evaluate(()=>window.__sockets.forEach(s=>s.close()));await b.page.waitForFunction(()=>['DISCONNECTED','STALE'].includes(document.querySelector('.exhibit-status')?.textContent),null,{timeout:15000});await b.page.waitForTimeout(200);const heldStep=await b.page.locator('.specimen-panel').getAttribute('data-model-step');const image=await b.page.locator('.specimen-canvas').evaluate(c=>c.toDataURL());await b.page.waitForTimeout(1500);freeze=image===await b.page.locator('.specimen-canvas').evaluate(c=>c.toDataURL());assert.equal(await b.page.locator('.specimen-panel').getAttribute('data-model-step'),heldStep,'Disconnected model step must freeze');assert(freeze,'Disconnected specimen must freeze');await b.context.setOffline(false);await b.page.waitForFunction(()=>document.querySelector('.exhibit-status')?.textContent==='LIVE',null,{timeout:60000});offline=true;if(!restartWorker)recovered=true;}
   if(seconds>300&&restartWorker&&!restart){restart={at:new Date().toISOString(),before:state.planner,completed:false};console.log('CONTROLLED_WORKER_RESTART_STARTED');restart.promise=workerRestart().then(out=>{Object.assign(restart,out,{completed:true});}).catch(e=>{restart.error=e.message;});}
   if(restart?.completed&&samples.at(-1).presentation.health==='LIVE'&&state.health.seq>0&&state.planner.recent.some(v=>Date.parse(v.at)>Date.parse(restart.completedAt)))recovered=true;
  }
  if(samples.length%10===0)console.log(JSON.stringify({seconds:Math.round(seconds),matching,visits:visits.size,memoryChoices:[...choices.values()].filter(c=>c.memoryChangedSelection).length,narrator:state.journal.narrator.state,recovered}));
  await a.page.waitForTimeout(2000);
 }
 const seconds=(Date.now()-started)/1000;
 await a.page.screenshot({path:root+'/observe-1920.png',fullPage:true});
 if(!endurance){await a.context.close();await video.saveAs(root+'/integrated.webm');await video.delete();a=await observer();
  for(const path of ['/','/specimens','/memory','/inside','/experiments'])for(const width of [1920,390]){await a.page.setViewportSize({width,height:width===390?844:1080});const response=await a.page.goto(base+path);assert.equal(response.status(),200);await a.page.waitForTimeout(2000);const layout=await a.page.evaluate(()=>({width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth,body:parseFloat(getComputedStyle(document.querySelector('.showcase')).fontSize),stage:document.querySelector('.observation-stage')?.getBoundingClientRect().height,heading:document.querySelector('h1')?.textContent}));assert(!layout.overflow,`${path} ${width} overflows`);assert(layout.body>=16);layouts.push({path,...layout});await a.page.screenshot({path:root+'/'+(path.slice(1)||'observe')+'-'+width+'.png',fullPage:true});}
  await a.page.setViewportSize({width:1920,height:1080});await a.page.goto(base+'/');await a.page.waitForSelector('.journal-entry');await a.page.getByRole('button',{name:'Pause',exact:true}).click();const paused=await a.page.locator('.journal-scroll').innerText();await a.page.waitForTimeout(5000);assert.equal(await a.page.locator('.journal-scroll').innerText(),paused);await a.page.getByRole('button',{name:'Follow live',exact:true}).click();await a.page.getByRole('button',{name:'Inspect ↗',exact:true}).last().click();await a.page.waitForSelector('[role=dialog]');await a.page.keyboard.press('Escape');assert.equal(await a.page.locator('[role=dialog]').count(),0);await a.page.getByLabel('Journal event filter').selectOption('QUESTION');await a.page.waitForTimeout(4500);assert(await a.page.locator('.type-question').count()>0);
  await a.page.goto(base+'/memory');await a.page.locator('.memory-card').first().click();await a.page.waitForSelector('.memory-story-intro');await a.page.screenshot({path:root+'/memory-detail.png',fullPage:true});
  await a.page.goto(base+'/inside');await a.page.waitForSelector('.trace-story');for(const title of ['Sense','Compute','Decode','Execute','Remember']){await a.page.getByRole('tab',{name:new RegExp(title)}).click();await a.page.waitForTimeout(500);}await a.page.screenshot({path:root+'/trace-remember.png',fullPage:true});
  for(const path of ['/docs/previews/external-review.html','/DOCS/PREVIEWS/external-review.html','/docs/previews%2Fexternal-review.html'])assert.equal((await fetch(base+path)).status,404,path);
  for(const path of ['/api/exhibit/external-preview','/api/exhibit/external-desktop']){const r=await fetch(base+path,{headers:{Range:'bytes=0-2047'}});assert.equal(r.status,206);assert((await r.arrayBuffer()).byteLength>0);}
 }
 if(restart?.promise)await restart.promise;
 const allChoices=[...choices.values()],allEntries=[...entries.values()],allVisits=[...visits.values()].sort((a,b)=>a.at.localeCompare(b.at));
 result={startedAt:new Date(started).toISOString(),at:new Date().toISOString(),observerAssets:await a.page.evaluate(()=>[...document.scripts].map(s=>s.src).filter(Boolean)),sourceRevision:live.sourceRevision,sourceDirty:live.sourceDirty,restartWorker,sessionId:initial.sessionId,seconds,matching,paired,offline,freeze,recovered,restart:restart?{...restart,promise:undefined}:undefined,layouts,errors,visits:allVisits,choices:allChoices,journal:allEntries,narrator:samples.at(-1).narrator};
 assert.equal(errors.length,0);assert(allEntries.some(e=>e.owner==='semantic-narrator'&&e.model),'No actual semantic narration');assert(allChoices.some(c=>c.memoryChangedSelection),'No memory-driven destination difference');
 if(endurance){assert(allChoices.some(c=>c.memoryChangedSelection&&Date.parse(c.at)>=started),'No memory-driven choice during the sustained session');assert(allEntries.some(e=>e.model&&Date.parse(e.at)>=started),'No semantic entry during the sustained session');assert(matching>500);assert(offline&&freeze&&recovered);if(restartWorker){assert(!restart.error,restart.error);assert(allVisits.filter(v=>Date.parse(v.at)>Date.parse(restart.completedAt)).length>=3);}assert(new Set(allVisits.filter(v=>Date.parse(v.at)>=started).map(v=>new URL(v.url).hostname)).size>=3);assert(allVisits.filter(v=>Date.parse(v.at)>=started).length>=8);}
 console.log(JSON.stringify({passed:true,root,seconds,matching,paired,visits:allVisits.length,memoryChoices:allChoices.filter(c=>c.memoryChangedSelection).length,semanticEntries:allEntries.filter(e=>e.model).length,recovered,layouts:layouts.length}));
}catch(e){result={...result,error:e.message};console.error(e);process.exitCode=1;}finally{writeFileSync(root+'/result.json',JSON.stringify({...result,samples,observedChoices:[...choices.values()],observedVisits:[...visits.values()]},null,2));await browser.close();}
