import fs from 'node:fs';import {gunzipSync} from 'node:zlib';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
import {ExhibitController} from '../server/exhibit/controller';import {motorReadout} from '../server/browser/decoder';import {decodeExhibit} from '../server/exhibit/controller';
const root=process.argv[2]??'runtime/social-film/source',r=JSON.parse(fs.readFileSync(root+'/record.json','utf8')),trace=JSON.parse(gunzipSync(fs.readFileSync(root+'/trace.json.gz')).toString()),circuit=JSON.parse(fs.readFileSync('data/processed/circuit.json','utf8')),hash=(b:Buffer)=>createHash('sha256').update(b).digest('hex');
assert.equal(hash(fs.readFileSync('data/processed/circuit.json')),r.origin.dataSha256);
for(const name of ['browser.webm','trace.json.gz','display-timing.json.gz','frame-0054.png','frame-0055.png']){const a=r.artifacts.find((a:any)=>a.path===name);assert(a);const b=fs.readFileSync(root+'/'+name);assert.equal(hash(b),a.sha256);assert.equal(b.length,a.bytes);}
assert.deepEqual(trace.map(({samples,...d}:any)=>d),r.decisions);
const controller=new ExhibitController(circuit,r.id,r.startedAt,r.intervention);controller.engine.restore(r.initialCheckpoint);let samples=0,pixelWindows=0;
for(const d of trace){const png=root+'/'+d.imageBefore;if(d.decision===27){const calculated=await controller.observe(fs.readFileSync(png),d.decision,undefined,d.sensoryProfile);for(const k of ['input','motor','command','modelStartStep','modelEndStep'])assert.deepEqual((calculated as any)[k],d[k]);calculated.samples.forEach((s:any,i:number)=>{for(const k of ['activity','sensory','motor','pose','modelTime','seq'])assert.deepEqual(s[k],d.samples[i][k]);samples++;});pixelWindows++;}else{controller.engine.condition={key:'pixels',label:'scroll: '+d.input.encoding,intensity:(d.input.left+d.input.right)/2,angle:0,epoch:d.decision};for(let i=0;i<r.config.modelSteps;i++){controller.engine.step({left:d.input.left,right:d.input.right});if((i+1)%r.config.sampleEvery===0){const s=controller.engine.snapshot(r.id,controller.engine.ticks,r.startedAt,0),saved=d.samples[(i+1)/r.config.sampleEvery-1];for(const k of ['activity','sensory','motor','pose','modelTime','seq'] as const)assert.deepEqual(s[k],saved[k]);samples++;}}assert.deepEqual(decodeExhibit(motorReadout(circuit,controller.engine.network.activity),'scroll'),d.command);}}
const d=trace[27],memory=JSON.parse(fs.readFileSync(root+'/memory.json','utf8')),e=memory.encounter.evidence.find((e:any)=>e.commandId===d.commandId);assert(e);assert.equal(e.runId,d.runId);assert.equal(e.decision,d.decision);assert.equal(e.at,d.receipt.observedAt);assert.equal(e.displacement,d.receipt.scrollAfter-d.receipt.scrollBefore);assert.equal(e.status,'moved');assert.equal(d.memory.storedId,memory.encounter.id);assert.equal(d.receipt.trustedEvents,1);assert.equal(d.command.wheelY,48);assert.equal(d.receipt.status,'moved');
const pub=JSON.parse(fs.readFileSync(root+'/publication.json','utf8'));assert.equal(hash(fs.readFileSync(root+'/published-record.json')),pub.recordSha256);
const result={at:new Date().toISOString(),runId:r.id,commandId:d.commandId,sourceRevision:r.origin.sourceRevision,recordedInputReplay:{exact:true,decisions:trace.length,samples},selectedPixelReplay:{exact:true,decision:27,windows:pixelWindows,samples:60,inputSha256:d.imageSha256},nativeReceipt:{status:d.receipt.status,wheelY:d.command.wheelY,scrollBefore:d.receipt.scrollBefore,scrollAfter:d.receipt.scrollAfter,trustedEvents:d.receipt.trustedEvents,observedAt:d.receipt.observedAt},memory:{id:memory.encounter.id,title:memory.encounter.title,url:memory.encounter.url,evidenceAt:e.at,commandMatched:true},publication:pub};fs.writeFileSync('runtime/social-film/evidence-verification.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
