import { useEffect,useState } from 'react';
import type { ExhibitRecord,ExhibitDecision } from '../shared/exhibit';
import type { Publication } from '../server/experiment-store';
type Row=Omit<ExhibitRecord,'decisions'>&{decisions:number;actions:number;artifactsAvailable:boolean};
export function ExhibitArchive({onInspect}:{onInspect:(d:ExhibitDecision,record?:ExhibitRecord)=>void}){
  const [rows,setRows]=useState<Row[]>([]),[pubs,setPubs]=useState<Publication[]>([]),[expanded,setExpanded]=useState<ExhibitRecord|null>(null),[error,setError]=useState('');
  useEffect(()=>{let active=true;async function update(){try{const [r,p]=await Promise.all(['/api/exhibit/records','/api/exhibit/publications'].map(url=>fetch(url).then(r=>r.json())));if(active){setRows(r);setPubs(p);}}catch{}}void update();const t=setInterval(update,5000);return()=>{active=false;clearInterval(t);};},[]);
  async function inspect(id:string,index:number){try{const r=await fetch(`/api/exhibit/decision/${id}/${index}`);if(!r.ok)throw new Error((await r.json()).error);onInspect(await r.json(),expanded??undefined);setError('');}catch(e){setError((e as Error).message);}}
  return <section className="exhibit-archive panel"><div className="panel-heading"><span>E / OBSERVATION ARCHIVE</span><a href="/docs/evidence/browser/index.html" target="_blank" rel="noreferrer">Frozen baseline & controls ↗</a></div><p className="archive-intro">Completed episodes, including failures. Specimen Recorder publishes at episode boundaries. Raw traces and video retain eight local episodes; compact records retain provenance.</p><div className="table-scroll"><table><thead><tr><th>Run / source</th><th>Condition</th><th>Outcome</th><th>Actions</th><th>Publication</th><th>Evidence</th></tr></thead><tbody>{rows.map(r=>{const p=pubs.find(p=>p.id===r.id);return <tr key={r.id}><td><b>{r.id.slice(-8)}</b><small>{r.origin.sourceRevision.slice(0,7)}{r.origin.sourceDirty?' · working tree':''}</small></td><td>{r.intervention}<small>{r.layout} / seed {r.seed}</small></td><td>{r.outcome}</td><td>{r.actions} / {r.decisions}</td><td>{p?.state==='published'?<a href={p.url} target="_blank" rel="noreferrer">{p.commit?.slice(0,7)} ↗</a>:<span title={p?.reason}>{p?.state??'pending'}<small>{p?.reason}</small></span>}</td><td><button onClick={()=>void fetch('/api/exhibit/record/'+r.id).then(r=>r.json()).then(setExpanded)}>Inspect</button></td></tr>;})}</tbody></table>{!rows.length&&<p className="archive-intro">First continuous episode in progress. The frozen nine-trial baseline is available above.</p>}</div>
    {expanded&&<div className="archive-expanded"><div className="expand-title"><b>{expanded.id}</b><button onClick={()=>setExpanded(null)}>Close</button></div><p>{expanded.error??expanded.setup.note}</p><div className="archive-links"><a href={`/api/exhibit/record/${expanded.id}`} target="_blank" rel="noreferrer">Compact record</a><a href={`/api/exhibit/artifacts/${expanded.id}/trace.json.gz`}>Neural trace</a><a href={`https://github.com/SpecimenArchive/Specimen-Archive/tree/${expanded.origin.sourceRevision}`} target="_blank" rel="noreferrer">Executed source</a></div><video controls preload="none" src={`/api/exhibit/artifacts/${expanded.id}/browser.webm`}/><div className="decision-buttons">{expanded.decisions.map(d=><button key={d.commandId} onClick={()=>void inspect(expanded.id,d.decision)}>D{d.decision+1} · {d.command.kind}</button>)}</div></div>}{error&&<p role="alert">{error}</p>}</section>;
}
