import { useEffect,useState } from 'react';
import type { Circuit,Snapshot } from '../shared/types';
import type { ExhibitLive,ExhibitDecision,ExhibitRecord } from '../shared/exhibit';
import { useExhibit } from './useExhibit';
import { SpecimenView } from './SpecimenView';
import { NetworkView } from './NetworkView';
import { NeuronTrace } from './NeuronTrace';
import { ActivityHistory } from './ActivityHistory';
import { Apparatus } from './Apparatus';
import { usePresentation } from './usePresentation';
import { ExhibitArchive } from './ExhibitArchive';
import { App as LegacyApp } from './App';
import './exhibit.css';
const artifact=(path:string|null)=>path?'/api/exhibit/artifacts/'+path:undefined;
export function App(){const [mode,setMode]=useState('exhibit');useEffect(()=>{fetch('/api/health').then(r=>r.json()).then(h=>setMode(h.mode));},[]);return mode==='exhibit'?<Exhibit/>:<LegacyApp/>;}
function Exhibit(){
  const stream=useExhibit(),[circuit,setCircuit]=useState<Circuit|null>(null),[selected,setSelected]=useState('1732111'),[replay,setReplay]=useState<{d:ExhibitDecision;record?:ExhibitRecord}|null>(null),[sampleIndex,setSampleIndex]=useState(59),[playing,setPlaying]=useState(false),[error,setError]=useState('');
  useEffect(()=>{fetch('/api/circuit').then(r=>r.json()).then(setCircuit);},[]);
  useEffect(()=>{if(!playing||!replay)return;const timer=setInterval(()=>setSampleIndex(i=>{if(i>=replay.d.samples.length-1){setPlaying(false);return i;}return i+1;}),50);return()=>clearInterval(timer);},[playing,replay]);
  function inspect(d:ExhibitDecision,record?:ExhibitRecord){setReplay({d,record});setSampleIndex(d.samples.length-1);setPlaying(false);document.getElementById('connected-views')?.scrollIntoView({behavior:'smooth',block:'start'});}
  async function inspectEvent(runId:string,decision:number){try{const r=await fetch(`/api/exhibit/decision/${runId}/${decision}`);if(!r.ok)throw new Error((await r.json()).error);inspect(await r.json());setError('');}catch(e){setError((e as Error).message);}}
  const l=stream.live,d=replay?.d,requestedSnapshot:Snapshot|null=d?d.samples[sampleIndex]:l?.snapshot??null;
  const requested:ExhibitLive|null=d&&l?{...l,...d.context,runId:d.runId,sessionId:d.sessionId,state:'executed',decision:d.decision,inputFrame:`${d.runId}/${d.imageBefore}`,browserFrame:`${d.runId}/${sampleIndex===d.samples.length-1?d.imageAfter:d.imageBefore}`,desktop:(sampleIndex===d.samples.length-1?d.desktopAfter:d.desktopBefore)??null,snapshot:requestedSnapshot,input:d.input,motor:d.motor,command:d.command,commandId:d.commandId,capturedAt:d.capturedAt,history:[{commandId:d.commandId,runId:d.runId,decision:d.decision,modelStep:d.modelEndStep,kind:d.command.kind,detail:d.executed.events.map(e=>e.type).join(' → ')||'No input event',timestamp:d.completedAt}],notice:'Recorded observation. No browser commands execute during replay.'}:l;
  const presentation=usePresentation(requested),shown=presentation.live,s=shown?.snapshot??null;
  const frames=(d?d.samples.slice(0,sampleIndex+1):stream.history.current).filter(frame=>frame.runId===s?.runId&&frame.seq<=s.seq),health=d?'replay':stream.health,index=circuit?.nodes.findIndex(n=>n.id===selected)??-1,cell=circuit?.nodes[index];
  const motors=circuit?.nodes.flatMap((n,i)=>n.category==='motor'?[{...n,value:s?.activity[i]??0}]:[])??[],mean=motors.reduce((sum,n)=>sum+n.value,0)/6,contrast=(motors.find(n=>n.id==='1732111')?.value??0)-(motors.find(n=>n.id==='359142')?.value??0);
  return <div className="exhibit-shell"><header className="exhibit-header"><a className="archive-mark" href="/"><span className="logo-mark">✳</span><span>SPECIMEN<br/><b>ARCHIVE</b></span></a><span className="exhibit-edition">OBSERVATION SERIES / 001</span><a href="/docs/WORKSHEET.html" target="_blank" rel="noreferrer">Methods & worksheet ↗</a><span className="exhibit-status"><i className={`status-dot ${health}`}/>{health.toUpperCase()}</span></header>
    <main><div className="exhibit-title"><div><div className="eyebrow">CONTINUOUS OBSERVATION / ONE SHARED SESSION</div><h1>Specimen <span>01</span><small>$LARVA</small></h1></div><div className="species"><i>Platynereis dumerilii</i><span>MARINE ANNELID · 72 HPF</span></div></div>
      <Apparatus live={shown} desktopImage={presentation.desktopImage}/>
      <div className="session-line" data-session-id={shown?.sessionId} data-run-id={shown?.runId} data-model-step={s?.seq}><span><i className={`status-dot ${health}`}/> {d?'ARCHIVE REPLAY':shown?.state.toUpperCase()??'CONNECTING'} · {d?d.context?.intervention??'recorded window':'INTACT'}</span><span>EPISODE {(shown?.episode??0)+1} / D{(shown?.decision??0)+1}</span><span>MODEL {s?.modelTime.toFixed(1)??'0.0'} s · STEP {s?.seq??0}</span><span title={shown?.runId}>{shown?.runId.slice(-8)??'—'} · {shown?.sourceRevision.slice(0,7)}{shown?.sourceDirty?' *':''}</span></div>
      {d&&<div className="replay-bar"><b>REPLAY · OBSERVER ONLY</b><button onClick={()=>{if(sampleIndex>=d.samples.length-1)setSampleIndex(0);setPlaying(!playing);}}>{playing?'Pause':'Play window'}</button><input aria-label="Recorded neural sample" type="range" min="0" max={d.samples.length-1} value={sampleIndex} onChange={e=>{setPlaying(false);setSampleIndex(Number(e.target.value));}}/><button onClick={()=>{setReplay(null);setPlaying(false);}}>Return to current session</button></div>}
      <div className="connected-views" id="connected-views">
        <section className="specimen-panel panel" data-run-id={shown?.runId} data-model-step={s?.seq}><div className="panel-heading"><span>B / SPECIMEN FIELD</span><span>72 hpf</span></div><div className="microscope"><SpecimenView snapshot={s} circuit={circuit}/><span className="field-label">DORSOVENTRAL / FIXED OBSERVATION ANGLE</span><span className="field-mode">LOCAL TISSUE RESPONSE · TRANSMITTED LIGHT</span>{!s&&<div className="signal-overlay">Establishing observation</div>}</div><div className="specimen-footer"><div><label>POSTURAL BEND</label><b>{s?.pose.bend.toFixed(4)??'—'}</b></div><div><label>MOTOR L / R</label><b>{s?.motor.left.toFixed(3)??'—'} / {s?.motor.right.toFixed(3)??'—'}</b></div><div><label>MODEL / WALL</label><b>2× <small>during integration</small></b></div></div></section>
        <section className="signal-panel panel" data-run-id={shown?.runId} data-model-step={s?.seq}><div className="panel-heading"><span>C / SIGNAL PATH</span><span>47 CELLS / 161 EDGES</span></div><div className="retina-block"><div><label>ACTUAL INPUT FRAME</label><a href={artifact(shown?.inputFrame??null)} target="_blank" rel="noreferrer"><img src={artifact(shown?.inputFrame??null)} alt="Exact captured PNG supplied to the sensory encoder"/></a></div><div><label>PIXELS → 21 PRCs</label><strong>{shown?.input?.encoding??'—'}</strong><p>L {shown?.input?.left.toFixed(2)??'—'} / R {shown?.input?.right.toFixed(2)??'—'}<br/>Phase: {shown?.input?.phase??'—'}<br/>{shown?.input?.targetPixels??0} target pixels</p></div></div>
          {circuit&&<ActivityHistory frames={frames} circuit={circuit} selected={selected} onSelect={setSelected}/>}
          <div className="selected-neuron"><label>SELECTED NEURON / SOURCE ID</label><select aria-label="Inspect neuron" value={selected} onChange={e=>setSelected(e.target.value)}>{circuit?.nodes.map(n=><option key={n.id} value={n.id}>{n.name} · #{n.id}</option>)}</select><span>{cell?.category} · activity {(s?.activity[index]??0).toFixed(5)}</span></div>
          {circuit&&<NeuronTrace circuit={circuit} selected={selected} frames={frames}/>}
          <div className="motor-decoder"><label>SIX MOTOR OUTPUTS → DECODER</label><div className="motor-cells">{motors.map(n=><button onClick={()=>setSelected(n.id)} key={n.id} title={`Published neuron #${n.id}`}>{n.name}<b>{n.value.toFixed(4)}</b></button>)}</div><div className="thresholds"><span>M <b>{mean.toFixed(4)}</b> / gate .500 / click .593</span><span>D <b>{contrast.toFixed(4)}</b> / direction .008</span></div></div>
          <details className="circuit-detail"><summary>Published connectivity / functional layout</summary>{circuit&&<NetworkView circuit={circuit} snapshot={s} selected={selected} onSelect={setSelected}/>}<p>Schematic positions. Dimensionless rate activity; no spike, voltage or calcium measurement.</p></details>
        </section>
        <section className="controlled-panel panel" data-run-id={shown?.runId} data-model-step={s?.seq}><div className="panel-heading"><span>D / CONTROLLED BROWSER</span><span>VIEW ONLY</span></div><div className="controlled-image">{shown?.browserFrame?<a href={artifact(shown.browserFrame)} target="_blank" rel="noreferrer"><img src={artifact(shown.browserFrame)} alt="Actual Playwright-controlled browser, including cursor and page state"/></a>:<div>Opening controlled browser…</div>}</div><div className="browser-explanation"><label>PIXELS → PRCs → INTERNEURONS → MOTORS → PLAYWRIGHT</label><h2>{shown?.command?`${shown.command.kind==='wait'?'Motor gate closed':shown.command.kind==='scroll'?`Scroll ${shown.command.wheelY} px`:shown.command.kind==='move'?`Cursor ${shown.command.dx} px`:'Activate at cursor'}`:'Integrating the captured image'}</h2><p>{shown?.notice}</p><small>Image: {shown?.browserFrame?.split('/')[1]??'—'}<br/>Input captured: {shown?.capturedAt?.slice(11,23)??'—'} UTC<br/>Commands after 6.00 model seconds / 600 steps.</small></div>
          <div className="action-feed"><label>THIS RUN / SELECT AN ACTION TO TRACE IT</label>{(shown?.history??[]).slice(-5).reverse().map(h=><button key={h.commandId} onClick={()=>void inspectEvent(h.runId,h.decision)}><span>D{h.decision+1}<b>{h.kind}</b></span><span>{h.detail}<small>STEP {h.modelStep} · {h.timestamp.slice(11,19)} UTC ↗</small></span></button>)}</div>
        </section>
      </div>
      {error&&<p role="alert">{error}</p>}
      {d&&<section className="causal-chain panel"><div className="panel-heading">RECORDED CAUSAL CHAIN / {d.commandId}</div><div><p><b>1. Capture</b> {d.capturedAt} · SHA256 <code>{d.imageSha256}</code></p><p><b>2. Encode</b> {d.input.encoding} → L {d.input.left}, R {d.input.right}; {d.input.targetPixels} target pixels. Phase {d.input.phase}.</p><p><b>3. Compute</b> Steps {d.modelStartStep}–{d.modelEndStep}; {d.samples.length} samples of all 47 neurons. Inspect any neuron above.</p><p><b>4. Decode</b> M {d.motor.mean.toFixed(8)} / D {d.motor.contrast.toFixed(8)} → {d.command.kind}. {d.command.reason}.</p><p><b>5. Execute</b> {d.executed.startedAt}–{d.executed.completedAt}. {d.executed.events.map(e=>e.type).join(' → ')||'No input event; gate closed'}.</p><p><b>6. Recapture</b> {d.completedAt} · SHA256 <code>{d.afterSha256}</code>. This PNG is the next input.</p><a href={`/api/exhibit/decision/${d.runId}/${d.decision}`} target="_blank" rel="noreferrer">Complete linked event and neural record ↗</a></div></section>}
      <ExhibitArchive onInspect={inspect}/><footer><span>SPECIMEN ARCHIVE / OBSERVATION 001</span><span>{shown?.sessionId??'CONNECTING'} · OBSERVATION ONLY</span><a href="https://github.com/SpecimenArchive/Specimen-Archive" target="_blank" rel="noreferrer">Source repository ↗</a></footer>
    </main></div>;
}
