import {useEffect,useState} from 'react';import type {Experience,MemoryView,Recall} from '../shared/memory';
import './memory.css';
export function MemoryPanel({onInspect}:{onInspect:(run:string,decision:number)=>void}){
 const [view,setView]=useState<MemoryView|null>(null),[selected,setSelected]=useState<{encounter:Experience;recalls:Recall[]}|null>(null),[error,setError]=useState('');
 useEffect(()=>{let disposed=false;const read=async()=>{try{const r=await fetch('/api/memory');if(r.ok){const v=await r.json();if(!disposed)setView(v);}}catch{}};void read();const timer=setInterval(read,5000);return()=>{disposed=true;clearInterval(timer);};},[]);
 async function inspect(id:string){try{const r=await fetch('/api/memory/'+id);if(!r.ok)throw new Error('This memory has left the bounded store.');setSelected(await r.json());setError('');}catch(e){setError((e as Error).message);}}
 if(!view)return null;const recall=view.recall,evaluation=view.learning.evaluation,profile=view.selfProfile;
 return <section className="memory-section panel"><div className="panel-heading"><span>MEMORY / EXPERIENCES & SOURCED KNOWLEDGE</span><span>{view.stored} STORED · {view.retrieved} RECALLS · {view.used} USED BY SUPERVISOR</span></div>
  <div className="memory-content"><div className="memory-encounters">{view.recent.slice(0,4).map(m=><button key={m.id} onClick={()=>void inspect(m.id)}><img src={'/api/exhibit/artifacts/'+m.thumbnail} alt="Recorded encounter thumbnail" onError={e=>{e.currentTarget.style.visibility='hidden';}}/><span><b>{m.title}</b><small>{m.outcomes.moved??0} moves · {m.outcomes.boundary??0} boundary no-ops · {m.count} observed decisions</small></span></button>)}</div>
  <div className="memory-recall">{recall?.retrievedIds.length?<div className="recall-highlight" key={recall.id}><label>ACTUAL RECALL · {recall.at.slice(11,19)} UTC</label><p>{recall.matches.map(m=><button key={m.id} className="text-button" onClick={()=>void inspect(m.id)}>{m.methods.join(' + ')}{m.visualDistance!==null?` · visual distance ${m.visualDistance.toFixed(2)}`:''}</button>)}</p><small>{recall.effect?.description??'Retrieved for inspection; no behaviour changed.'}</small>{recall.usedIds.length>0&&<button className="text-button" onClick={()=>onInspect(recall.runId,recall.decision)}>Used in this decision →</button>}</div>:<p className="panel-caption">{recall?'No matching prior encounter was retrieved for this context.':'Waiting for the first recorded external encounter.'}</p>}
   <div className="knowledge-notes">{view.notes.filter(n=>n.creator==='curated-knowledge').slice(0,2).map(n=><p key={n.id}><a href={n.source} target="_blank" rel="noreferrer">{n.title} ↗</a><span>{n.note}</span></p>)}</div>
  </div></div>
  {error&&<p role="alert">{error}</p>}
  {selected&&<div className="memory-detail"><button className="quiet-button" onClick={()=>setSelected(null)}>Close memory ×</button><h3>{selected.encounter.title}</h3><a href={selected.encounter.url} target="_blank" rel="noreferrer">Original public source ↗</a><p>{selected.encounter.id} · first observed {selected.encounter.createdAt} · updated {selected.encounter.updatedAt}</p><p>Identity uses canonical URL and title/address hash. Coarse visual matching is a separate 8 × 8 luminance comparison; it does not prove unique page recognition.</p><div className="memory-evidence">{selected.encounter.evidence.map(e=><button key={e.commandId} onClick={()=>onInspect(e.runId,e.decision)}>{e.at.slice(11,19)} · {e.status} · {e.displacement} px · inspect original decision ↗</button>)}</div><p>{selected.recalls.length} subsequent retrieval records. {selected.recalls.filter(r=>r.usedIds.includes(selected.encounter.id)).length} used by the supervisor.</p>{selected.recalls.slice(-3).map(r=><p key={r.id}>{r.at} · {r.reason}<br/>{r.effect?.description}</p>)}</div>}
  <details><summary>Factual self-profile & learning comparison</summary><div className="memory-profile"><div><h3>{profile.identity}</h3><p>{profile.model} · {profile.neurons} cells · {profile.edges} directed connections · {profile.synapses} anatomical synapses</p><p>{profile.task}</p><p>{profile.capabilities.join(' · ')}</p><p>{profile.limitations.join('. ')}.</p><small>Updated {profile.updatedAt} · <a href={`https://github.com/SpecimenArchive/Specimen-Archive/tree/${profile.sourceRevision}`}>configuration provenance ↗</a></small></div><div><h3>Supervisor retry adapter</h3><p>{view.learning.mode==='train'?'Collecting outcome evidence; the fixed baseline still controls retries.':view.learning.mode==='frozen'?'Using a frozen learned checkpoint; learning is stopped.':'Adaptation disabled; fixed baseline retries.'}</p><small>{view.learning.trainingEvents} training outcomes · checkpoint {view.learning.checkpoint.slice(0,12)}</small>{evaluation?<><p>{evaluation.result}</p><table><thead><tr><th>Frozen evaluation</th><th>Moved / attempts</th><th>Boundary no-ops</th></tr></thead><tbody>{(['baseline','adaptation','disabled'] as const).map(k=><tr key={k}><td>{k}</td><td>{evaluation[k].moved} / {evaluation[k].attempts}</td><td>{evaluation[k].boundary}</td></tr>)}</tbody></table><p>{evaluation.method}</p><small>{evaluation.limitations.join(' ')}</small></>:<p>Matched evaluation pending. Memory growth and stored outcomes are not evidence of improved behaviour.</p>}</div></div></details>
 </section>;
}
