import {DirectDesktop} from './DirectDesktop';
import {MemoryPanel} from './MemoryPanel';
import {useEffect,useState} from 'react';import type {Circuit,Snapshot} from '../shared/types';import type {ExhibitDecision,ExhibitLive,ExhibitRecord} from '../shared/exhibit';
import {ACTIVE_UNIT_THRESHOLD,observationHealth} from '../shared/observation';import {EXHIBIT_CONFIG as C} from '../server/exhibit/config';
import {useExhibit} from './useExhibit';import {usePresentation} from './usePresentation';import {Apparatus} from './Apparatus';import {SpecimenView} from './SpecimenView';import {ActivityHistory} from './ActivityHistory';import {NeuronTrace} from './NeuronTrace';import {NetworkView} from './NetworkView';import {ExhibitArchive} from './ExhibitArchive';import {ObservationFeed} from './ObservationFeed';import './observation.css';
const asset=(path:string|null|undefined)=>path?'/api/exhibit/artifacts/'+path:undefined;
const num=(value:number|null|undefined,digits=2)=>value===null||value===undefined||!Number.isFinite(value)?'—':value.toFixed(digits);
const elapsed=(seconds:number)=>`${Math.floor(Math.max(0,seconds)/60)}:${String(Math.floor(Math.max(0,seconds)%60)).padStart(2,'0')}`;
export function ObservationApp(){
 const workstation=new URLSearchParams(location.search).get('display')==='workstation',stream=useExhibit();
 const [circuit,setCircuit]=useState<Circuit|null>(null),[selected,setSelected]=useState('1732111'),[decision,setDecision]=useState<ExhibitDecision|null>(null),[sample,setSample]=useState(0),[playing,setPlaying]=useState(false),[error,setError]=useState(''),[now,setNow]=useState(Date.now()),[overlay,setOverlay]=useState(true);
 useEffect(()=>{fetch('/api/circuit').then(r=>r.json()).then(setCircuit).catch(()=>setError('Circuit metadata unavailable.'));const timer=setInterval(()=>setNow(Date.now()),500);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!playing||!decision)return;const timer=setInterval(()=>setSample(s=>{if(s>=decision.samples.length-1){setPlaying(false);return s;}return s+1;}),100);return()=>clearInterval(timer);},[playing,decision]);
 function inspect(d:ExhibitDecision,_record?:ExhibitRecord){setDecision(d);setSample(d.samples.length-1);setPlaying(false);setError('');}
 async function inspectEvent(run:string,index:number){try{const response=await fetch(`/api/exhibit/decision/${run}/${index}`);if(!response.ok)throw new Error('This event’s raw trace has left the bounded local archive.');inspect(await response.json());}catch(e){setError((e as Error).message);}}
 const live=stream.live,d=decision,source:ExhibitLive|null=d&&live?{...live,...d.context,runId:d.runId,sessionId:d.sessionId,state:'executed',display:null,receipt:d.receipt,lastAction:d.receipt?{runId:d.runId,decision:d.decision,commandId:d.commandId,input:d.input,motor:d.motor,command:d.command,receipt:d.receipt}:undefined,decision:d.decision,snapshot:d.samples[sample],input:d.input,inputFrame:`${d.runId}/${d.imageBefore}`,browserFrame:`${d.runId}/${sample===d.samples.length-1?d.imageAfter:d.imageBefore}`,desktop:(sample===d.samples.length-1?d.desktopAfter:d.desktopBefore)??null,motor:d.motor,command:d.command,commandId:d.commandId,capturedAt:d.capturedAt,notice:'Historical decision; the shared station continues.'}:live;
 const presentation=usePresentation(source,workstation),shown=presentation.live,s=shown?.snapshot??null,serverNow=stream.serverNow();
 const transport=observationHealth(stream.health,(live?.display??live?.desktop)?.capturedAt,serverNow,live?.state),health=d?'replay':transport;
 const frames=(d?d.samples.slice(0,sample+1):stream.history.current).filter(f=>f.runId===s?.runId&&f.seq<=s.seq),index=circuit?.nodes.findIndex(n=>n.id===selected)??-1,cell=circuit?.nodes[index];
 const motors=circuit&&s?circuit.nodes.flatMap((n,i)=>n.category==='motor'?[{...n,value:s.activity[i]}]:[]):[],mean=motors.length?motors.reduce((v,n)=>v+n.value,0)/motors.length:null,contrast=motors.length?(motors.find(n=>n.id==='1732111')!.value-motors.find(n=>n.id==='359142')!.value):null;
 const observation=live?.observation,metrics=observation?.metrics,input=shown?.input,sampling=input&&'sampling'in input?input.sampling:null,frameAge=(live?.display??live?.desktop)?Math.max(0,(serverNow-Date.parse((live!.display??live!.desktop)!.capturedAt))/1000):null;
 const sourceLink=(file:string)=>`https://github.com/SpecimenArchive/Specimen-Archive/blob/${shown?.sourceRevision||'master'}/${file}`;
 const started=observation?.sessionStartedAt??s?.startedAt,lastAction=shown?.lastAction;
 return <div className={`exhibit-shell observation-shell ${workstation?'workstation-display':''}`}><header className="exhibit-header"><a className="archive-mark" href="/"><span className="logo-mark">✳</span><span>SPECIMEN<br/><b>ARCHIVE</b></span></a><span className="exhibit-edition">A COMPUTATIONAL OBSERVATION / 001</span><a href="/docs/WORKSHEET.html" target="_blank" rel="noreferrer">Methods & worksheet ↗</a><span className="exhibit-status"><i className={`status-dot ${health}`}/>{health.toUpperCase()}</span></header>
 <main><div className="observation-title"><div><span className="eyebrow">THE OBSERVATION STATION</span><h1>Specimen 01 <small>$LARVA</small></h1></div><p><i>Platynereis dumerilii</i><span>72 hpf · larval neural circuit</span></p></div>
 <div className="session-line" data-session-id={shown?.sessionId} data-run-id={shown?.runId} data-model-step={s?.seq}><span><i className={`status-dot ${health}`}/>{d?'HISTORICAL DECISION':transport.toUpperCase()} <b>{shown?.intervention??'CONNECTING'}</b></span><span>SESSION <b>{started?elapsed((serverNow-Date.parse(started))/1000):'—'}</b></span><span className="session-operation">{d?d.page?.label??'Recorded page':observation?.activePage.label??shown?.state??'Preparing station'}</span><span>DESKTOP AGE <b>{num(frameAge,1)} s</b></span><span>MODEL <b>{num(s?.modelTime,1)} s</b></span></div>
 {d&&<div className="replay-bar"><b>HISTORICAL VIEW · THE VM CONTINUES</b><button onClick={()=>{if(sample>=d.samples.length-1)setSample(0);setPlaying(!playing);}}>{playing?'Pause replay':'Play decision'}</button><input aria-label="Recorded neural sample" type="range" min="0" max={d.samples.length-1} value={sample} onChange={e=>{setPlaying(false);setSample(Number(e.target.value));}}/><button onClick={()=>{setDecision(null);setPlaying(false);}}>Return to live</button></div>}
 <div className="observation-stage"><Apparatus live={shown} desktopImage={presentation.desktopImage} health={health}/><DirectDesktop live={shown} desktopImage={presentation.desktopImage} health={health}/></div>
 <div className="encounter-line"><label>CURRENT ENCOUNTER</label><b>{d?d.page?.label:observation?.encounter?.label??observation?.activePage.label??'Opening external observation'}</b><span>{observation?.encounter?.enteredAt.slice(11,19)} UTC · {observation?.encounter?.source??'orchestration'}</span>{observation?.encounter?.tokenAddress&&<code title="Token contract address">{observation.encounter.tokenAddress}</code>}</div>
 <div className="journey-strip" aria-label="Recent page journey; inspection only">{observation?.journey?.map(e=><button key={e.visitId} disabled={e.decision===undefined} onClick={()=>e.decision!==undefined&&void inspectEvent(e.runId,e.decision)} title={e.label+' · '+e.url}>{e.thumbnail&&<img src={asset(e.thumbnail)} alt=""/>}<span>{e.kind}<b>{e.label}</b></span></button>)}</div>
 <div className="compact-counters"><span>UNIQUE PAGES <b>{observation?.counters?.uniquePages??'—'}</b></span><span>COIN PAGES <b>{observation?.counters?.coinPages??'—'}</b></span><span>WHEEL ATTEMPTS <b>{observation?.counters?.attempted??'—'}</b></span><span>VISIBLE MOVES <b>{observation?.counters?.moved??'—'}</b></span><span>BOUNDARY NO-OPS <b>{observation?.counters?.boundary??'—'}</b></span><span>POLICY BLOCKS <b>{observation?.counters?.policyBlocked??'—'}</b></span><span>FAILED <b>{observation?.counters?.failed??'—'}</b></span></div>
 <div className="connected-views" id="connected-views">
  <section className="specimen-panel panel" data-run-id={shown?.runId} data-model-step={s?.seq}><div className="panel-heading"><span>B / SPECIMEN</span><span>MODEL RESPONSE</span></div><div className="microscope"><SpecimenView snapshot={s} circuit={circuit}/><span className="field-label">LOCAL TISSUE DEFORMATION</span><span className="field-mode">COMPUTED MOTION · 72 hpf</span>{!s&&<div className="signal-overlay">Awaiting model state</div>}{s&&!['live','replay'].includes(health)&&<div className="stale-ribbon">HELD STATE · {health.toUpperCase()}</div>}</div><div className="specimen-footer"><div><label>POSTURAL BEND</label><b>{num(s?.pose.bend,4)}</b></div><div><label>MOTOR L / R</label><b>{num(s?.motor.left,3)} / {num(s?.motor.right,3)}</b></div></div><p className="panel-caption">Generated specimen imagery deforms from the same streamed motor state. No physical movement is measured.</p></section>
  <section className="signal-panel panel" data-run-id={shown?.runId} data-model-step={s?.seq}><div className="panel-heading"><span>C / NEURAL INSTRUMENTS</span><span>{circuit?.nodes.length??'—'} CELLS · {circuit?.edges.length??'—'} EDGES</span></div>
   <div className="sensory-heading"><label>{d?'RECORDED DECISION INPUT':observation?.sensory==='previous-decision'?'LAST DECISION INPUT · BEFORE ACTION':'CURRENT SENSORY INPUT'}</label><button className="quiet-button" onClick={()=>setOverlay(!overlay)} aria-pressed={overlay}>Sampling {overlay?'on':'off'}</button></div>
   {workstation?<p className="panel-caption">Input image omitted here to prevent recursive capture. The same frame and sampling bands are visible in the observer console.</p>:shown?.inputFrame?<div className="sensory-image"><img src={asset(shown.inputFrame)} alt="Exact captured image supplied to the neural encoder"/>{overlay&&input&&<svg viewBox={`0 0 ${input.width} ${input.height}`} aria-label="Actual encoder sampling regions">{sampling?[sampling.upper,sampling.lower].map((b,i)=><g key={i}><rect {...b.bounds} className={i?'lower-band':'upper-band'}/><text x={b.bounds.x+10} y={b.bounds.y+23}>{i?'LOWER → RIGHT DRIVE':'UPPER → LEFT DRIVE'}</text></g>):<rect x="0" y="0" width={input.width} height={input.height} className="upper-band"/>}</svg>}</div>:<div className="no-sensory"><b>No current sensory sample</b><span>{shown?.state==='idle'?'The model is held during recorded orchestration.':'Waiting for a verified capture of the visible page.'}</span></div>}
   <div className="sensory-values"><div><label>LEFT DRIVE</label><b>{num(input?.left,3)}</b>{input&&<meter min="0" max="1" value={input.left} aria-label="Left encoded drive"/>}</div><div><label>RIGHT DRIVE</label><b>{num(input?.right,3)}</b>{input&&<meter min="0" max="1" value={input.right} aria-label="Right encoded drive"/>}</div><p>{input?.encoding??'No sample'} · {input?`${input.width} × ${input.height} pixels`:'capture pending'}<small>{shown?.inputFrame?.split('/')[1]??'—'} · {shown?.capturedAt?.slice(11,23)??'—'} UTC</small></p></div>
   <div className="decision-summary"><label>LAST ACTION EXPLAINED</label><p>Encoded L {num(lastAction?.input.left,3)} / R {num(lastAction?.input.right,3)} → motor M {num(lastAction?.motor.mean,4)}, D {num(lastAction?.motor.contrast,4)} → {lastAction?.command.kind??'integrating'} {lastAction?.command.wheelY||''}</p><b>{lastAction?.receipt.reason??'Waiting for an acknowledged decision'}</b>{lastAction&&<button className="text-button" onClick={()=>void inspectEvent(lastAction.runId,lastAction.decision)}>Inspect calculation and receipt →</button>}</div>
   <details className="instrument-details"><summary>All cells, connectivity & recorded traces</summary>   <div className="functional-circuit"><label>IMPLEMENTED CIRCUIT / FUNCTIONAL LAYOUT</label>{circuit&&<NetworkView circuit={circuit} snapshot={s} selected={selected} onSelect={setSelected}/>}<p>{circuit?.nodes.filter(n=>n.category==='sensory').length??'—'} sensory → {circuit?.nodes.filter(n=>n.category==='interneuron').length??'—'} interneurons → {circuit?.nodes.filter(n=>n.category==='motor').length??'—'} motors. Layout is schematic; brightness is recorded normalised activity.</p></div>
   {circuit&&<ActivityHistory frames={frames} circuit={circuit} selected={selected} onSelect={setSelected}/>}<div className="selected-neuron"><label htmlFor="selected-cell">SELECTED CELL</label><select id="selected-cell" aria-label="Inspect neuron" value={selected} onChange={e=>setSelected(e.target.value)}>{circuit?.nodes.map(n=><option value={n.id} key={n.id}>{n.name} · #{n.id}</option>)}</select><span>{cell?.category??'—'} · activity {num(s?.activity[index],5)}</span></div>{circuit&&<NeuronTrace circuit={circuit} selected={selected} frames={frames}/>}</details>
  </section>
  <ObservationFeed live={live} onInspect={(run,index)=>void inspectEvent(run,index)}/>
 </div>
 <MemoryPanel onInspect={(run,index)=>void inspectEvent(run,index)}/>
 <details className="diagnostics-details"><summary>Decoder, capture performance & source revision</summary>  <section className="controlled-panel panel" data-run-id={shown?.runId} data-model-step={s?.seq}><div className="panel-heading"><span>DECODER & CAPTURE DIAGNOSTICS</span><span>OBSERVATION ONLY</span></div>   <div className="motor-decoder"><label>MOTOR OUTPUT → WHEEL COMMAND</label><div className="decoder-readouts"><div><b>{num(mean,4)}</b><span>motor mean M</span></div><div><b>{num(contrast,4)}</b><span>directional contrast D</span></div></div><div className="gate-meter"><div style={{width:`${(mean??0)*100}%`}}/><i style={{left:`${C.motorGate*100}%`}}/><span>action gate {C.motorGate.toFixed(3)}</span></div><p>M below {C.motorGate.toFixed(3)} waits. Above the gate, D ≥ {C.rightContrast.toFixed(3)} requests +{C.scrollPixels} px; otherwise −{C.scrollPixels} px. The observation profile scrolls only.</p><div className="motor-cells">{motors.map(m=><button key={m.id} onClick={()=>setSelected(m.id)}>{m.name}<b>{num(m.value,4)}</b></button>)}</div><small>The preserved task profile also uses a {C.activationMean.toFixed(3)} click threshold.</small></div>
   <div className="health-panel"><label>CAPTURE & TIMING</label><dl><div><dt>Capture cadence</dt><dd>{num(metrics?.captureFPS,2)} fps <small>last 10 s</small></dd></div><div><dt>Decision interval</dt><dd>{num(metrics?.decisionIntervalMs===null?null:metrics?.decisionIntervalMs===undefined?null:metrics.decisionIntervalMs/1000,2)} s <small>last 20</small></dd></div><div><dt>Model / wall time</dt><dd>{num(metrics?.modelWallRatio,2)}× <small>last window</small></dd></div><div><dt>Desktop age</dt><dd>{num(frameAge,1)} s</dd></div><div><dt>Page → desktop offset</dt><dd>{num(shown?.desktop?.pageLagMs,0)} ms</dd></div><div><dt>Source revision</dt><dd><a href={sourceLink('server/exhibit/external-station.ts')}>{shown?.sourceRevision.slice(0,7)??'—'}{shown?.sourceDirty?' · uncommitted':''}</a></dd></div></dl></div>
  </section></details>
 {error&&<p className="observation-error" role="alert">{error}</p>}
 <section className="event-timeline panel"><div className="panel-heading"><span>SENSORY INPUT → NEURAL RESPONSE → RESULT</span><span>{d?'INSPECTING HISTORY':'LIVE DECISION TIMELINE'}</span></div><div className="timeline-events">{(live?.observation?.events.filter(e=>e.source==='neural'&&e.decision!==undefined&&['completed','blocked','failed'].includes(e.status))??[]).slice(-14).map(e=><button key={e.id} className={d?.commandId===e.commandId?'selected':''} onClick={()=>void inspectEvent(e.runId,e.decision!)}><span>{e.createdAt.slice(11,19)}</span><b>{e.kind==='scroll'?`${e.parameters?.wheelY} px`:e.kind}</b><small>D{e.decision!+1} · {e.status}</small></button>)}</div>{!live?.observation&&<p className="panel-caption">Detailed timeline appears when the upgraded observation runtime connects.</p>}</section>
 {d&&<section className="causal-chain panel"><div className="panel-heading">LAST ACTION EXPLAINED / {d.commandId}</div><div className="causal-steps"><p><b>01 / Capture</b>{d.page?.label??'Controlled page'} · {d.imageBefore}<small>{d.capturedAt} · SHA256 {d.imageSha256}</small></p><p><b>02 / Encode</b>{d.input.encoding} → left {num(d.input.left,5)}, right {num(d.input.right,5)}<small>Sampling values are from the source PNG above.</small></p><p><b>03 / Compute</b>{d.modelEndStep-d.modelStartStep} integration steps · {d.samples[0]?.activity.length} cells<small>Steps {d.modelStartStep}–{d.modelEndStep}; inspect each cell’s recorded trace.</small></p><p><b>04 / Decode</b>M = {num(d.motor.mean,8)} · D = {num(d.motor.contrast,8)}<small>{d.command.reason}</small></p><p><b>05 / Execute</b>{d.command.kind} {d.command.wheelY||d.command.dx||''}<small>{d.executed.events.map(e=>`${e.type}${e.trusted?' (trusted)':''}`).join(' → ')||'No OS input: legitimate wait'}</small></p><p><b>06 / Observe result</b>{d.imageAfter}<small>Scroll {d.executed.nativeInput?.scrollBefore??'—'} → {d.executed.nativeInput?.scrollAfter??'—'} px · {d.completedAt}</small></p></div><a className="causal-record" href={`/api/exhibit/decision/${d.runId}/${d.decision}`} target="_blank" rel="noreferrer">Complete immutable decision record ↗</a></section>}
 <details className="methods-details"><summary>How is the specimen connected? · Methods & limitations</summary><section id="how-it-works" className="system-explainer panel"><div className="panel-heading"><span>HOW THE SPECIMEN CONTROLS WINDOWS</span><a href="/docs/WORKSHEET.html">Methods & assumptions ↗</a></div><h2>A software connection to a model of larval neurons.</h2><div className="pipeline"><a href={sourceLink('server/exhibit/remote-desktop.ts')}><b>01</b><h3>Capture</h3><p>The visible Chrome page supplies exact pixels. The real Windows desktop is recorded separately.</p></a><a href={sourceLink('server/exhibit/observation-encoder.ts')}><b>02</b><h3>Sense</h3><p>Texture contrast in upper and lower image bands becomes numerical left/right sensory drive.</p></a><a href={sourceLink('server/model/network.ts')}><b>03</b><h3>Propagate</h3><p>{circuit?.nodes.length??'—'} implemented cells and {circuit?.edges.length??'—'} directed connections update normalised activity.</p></a><a href={sourceLink('server/exhibit/controller.ts')}><b>04</b><h3>Decode</h3><p>The six motor values set an action gate and direction. M &lt; {C.motorGate.toFixed(3)} means wait.</p></a><a href={sourceLink('server/exhibit/external-station.ts')}><b>05</b><h3>Execute & verify</h3><p>Chrome receives the wheel command. Trusted events and the next image record what actually happened.</p></a></div><p>Published anatomy supplies connectivity. Rate dynamics, positive effective signs, sensory encoding and action thresholds are modelling choices in code: connectivity alone does not specify a complete functioning brain. Page selection and fixed cursor placement are recorded orchestration. The larval circuit supplies wheel direction; it does not read language or select coins. The observation dashboard is never a browsing destination. The generated apparatus depicts the exhibit; it is not a physical neural recording.</p><p className="anatomy-counts">Full imported study: {circuit?.sourceCounts.nodes.toLocaleString()??'—'} nodes / {circuit?.sourceCounts.edges.toLocaleString()??'—'} edges. Runtime subset above. <a href={sourceLink('data/processed/circuit.json')}>Inspect the actual circuit data ↗</a></p></section>
 </details><details className="archive-details"><summary>Episode archive & reproducible evidence</summary><ExhibitArchive onInspect={inspect}/></details><footer><span>SPECIMEN ARCHIVE · OBSERVATION ONLY</span><span>{live?.sessionId??'CONNECTING'}</span><a href="https://github.com/SpecimenArchive/Specimen-Archive">Source & evidence ↗</a></footer></main></div>;
}

import './exploration.css';
