import {useEffect,useState} from 'react';import type {ExhibitLive} from '../shared/exhibit';import type {ObservationEvent} from '../shared/observation';import {collapseWaits,eventSentence} from '../shared/observation';
const time=(value:string)=>new Date(value).toLocaleTimeString('en-GB',{hour12:false});
export function ObservationFeed({live,onInspect}:{live:ExhibitLive|null;onInspect:(run:string,decision:number)=>void}){
 const [following,setFollowing]=useState(true),[held,setHeld]=useState<ObservationEvent[]>([]),[detail,setDetail]=useState<ObservationEvent|null>(null);
 const events=live?.observation?.events??(live?.history??[]).map(h=>({id:h.commandId,commandId:h.commandId,runId:h.runId,sessionId:live!.sessionId,source:'neural' as const,kind:h.kind,status:'completed' as const,createdAt:h.timestamp,completedAt:h.timestamp,page:'Controlled page',summary:h.detail,decision:h.decision,modelStep:h.modelStep}));
 useEffect(()=>{if(following)setHeld(events);},[live?.packetSeq,following]);
 const shown=following?events:held,rows=collapseWaits(shown).slice(-12).reverse(),queue=live?.observation?.queue??[],last=[...events].reverse().find(e=>e.source==='neural'&&['completed','blocked','failed'].includes(e.status));
 function inspect(event:ObservationEvent){setFollowing(false);setHeld(events);setDetail(event);if(event.commandId&&event.decision!==undefined)onInspect(event.runId,event.decision);}
 return <aside className="observation-feed panel" aria-label="Live activity and command feed"><div className="panel-heading"><span>ACTIVITY LOG</span><button className="quiet-button" onClick={()=>{setFollowing(!following);setDetail(null);}}>{following?'Pause follow':'Follow live'}</button></div>
  <div className="feed-now"><label>NOW <span className="feed-source">{live?.observation?.sensory==='current'?'NEURAL MODEL':'STATION'}</span></label><h2>{live?.observation?.operation??live?.notice??'Connecting to the station'}</h2><p>{live?.observation?.activePage.label??'Waiting for page identity'}<span>{following?'Following the shared session':'Recent rows held for inspection; station continues'}</span></p></div>
  <div className="feed-queue"><label>QUEUED <span>{queue.length} accepted</span></label>{queue.slice(0,2).map(e=><div className="queue-entry" key={e.id}><i>↳</i><span>{e.summary}<small>{e.source==='neural'?'Neural decoder':'Orchestration'} · {e.status}</small></span></div>)}{queue.length>2&&<small>{queue.length-2} further scheduled changes</small>}{!queue.some(e=>e.source==='neural')&&<p className="awaiting">Awaiting next neural decision</p>}</div>
  <div className="feed-recent"><label>RECENT <span>{following?'LIVE':'FOLLOW PAUSED'}</span></label><div className="feed-scroll">{rows.map(({event,count,firstAt,lastAt})=><button className={`feed-event ${event.status} ${event.source}`} key={event.id} onClick={()=>inspect(event)}><div><time>{time(event.completedAt??event.createdAt)}</time><b>{event.kind}{count>1?` ×${count}`:''}</b><em>{event.status}</em></div><p>{event.kind==='wait'?event.reason??event.summary:event.summary}</p><small>{event.source==='neural'?'Neural decoder':'Orchestration'} · {event.page}{count>1?` · ${Math.max(0,(Date.parse(lastAt)-Date.parse(firstAt))/1000).toFixed(0)} s`:''}</small></button>)}{!rows.length&&<p className="empty-note">Events appear after the station accepts an operation.</p>}</div></div>
  {detail?.source==='orchestration'&&<div className="feed-detail"><b>{detail.summary}</b><p>{detail.reason??'Scheduled station maintenance; no neural decision is claimed.'}</p><small>{detail.id}</small></div>}
  <div className="last-action"><label>LAST ACTION EXPLAINED</label><p>{last?eventSentence(last):'No completed neural decision yet.'}</p>{last?.decision!==undefined&&<button className="text-button" onClick={()=>inspect(last)}>Inspect the calculation ↗</button>}</div>
 </aside>;
}
