import {useEffect,useRef,useState} from 'react';
import type {JournalEntry,JournalView} from '../../shared/journal';
import {usePublicData,actionLink,time} from './data';
export function Journal({visitId,full=false}:{visitId?:string;full?:boolean}){
 const [before,setBefore]=useState(''),[filter,setFilter]=useState(''),[held,setHeld]=useState<JournalView|null>(null),[pausedVisit,setPausedVisit]=useState<string>(),[selected,setSelected]=useState<JournalEntry|null>(null),[detailError,setDetailError]=useState('');
 const query=new URLSearchParams({...(before?{before}:{}),...(filter?{kind:filter}:{})}),request=usePublicData<JournalView>('/api/journal?'+query,4000),view=held??request.data,scroll=useRef<HTMLDivElement>(null),handledProposal=useRef('');
 useEffect(()=>{if(!held&&!before&&scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight;},[view?.updatedAt,held,before,filter]);
 async function inspect(id:string){try{const r=await fetch('/api/journal/'+id);if(!r.ok)throw Error();setSelected(await r.json());setDetailError('');}catch{setDetailError('This entry is no longer in the retained journal. Its linked experiment may still be available.');}}
 useEffect(()=>{const id=new URLSearchParams(location.search).get('entry');if(id)void inspect(id);},[]);
 useEffect(()=>{const id=new URLSearchParams(location.search).get('proposal');if(id&&handledProposal.current!==id){const entry=request.data?.entries.find(e=>e.proposalId===id);if(entry){handledProposal.current=id;void inspect(entry.id);}}},[request.data?.entries.length]);
 useEffect(()=>{if(!selected)return;const previous=document.activeElement as HTMLElement;document.querySelector<HTMLButtonElement>('.close-detail')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setSelected(null);if(e.key==='Tab'){const nodes=[...document.querySelectorAll<HTMLElement>('.detail-sheet button,.detail-sheet a,.detail-sheet summary')],first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[selected?.id]);
 return <section className={`live-journal ${full?'journal-full':''}`} aria-label="Live Journal"><div className="journal-title"><div><span className="kicker">FIELD NOTES / 01</span><h2>Live Journal<span className="journal-cursor" aria-hidden="true">_</span></h2></div><button onClick={()=>{setHeld(held?null:request.data);setPausedVisit(held?undefined:visitId);setBefore('');}} aria-pressed={!!held}>{held?'Follow live':'Pause'}</button></div>
 <div className="journal-tools"><label><span className="sr-only">Journal event filter</span><select aria-label="Journal event filter" value={filter} onChange={e=>{setFilter(e.target.value);setHeld(null);setBefore('');}}><option value="">All entries</option>{['OBSERVE','RECALL','CONNECT','QUESTION','NEXT','ACT','RESULT'].map(k=><option key={k}>{k}</option>)}</select></label><a href="/journal">History ↗</a><span>{held?'Reading paused':before?'Earlier entries':'Following'}</span></div>
 <div className="journal-scroll" ref={scroll} aria-live="off">{view?.entries.map(e=><article className={'journal-entry type-'+e.kind.toLowerCase()} key={e.id}><div className="journal-meta"><b>{e.kind}</b><time dateTime={e.at}>{e.at.slice(11,19)}</time><span>{e.status==='interpretation'?'interpretation':e.status==='proposed'?'proposed':e.status==='accepted'?'accepted':e.status==='failed'?'not verified':e.count>1?'×'+e.count:''}</span></div><p>{e.text}</p>{e.kind==='NEXT'&&e.evidence.destination&&<a className="journal-destination" href={e.evidence.destination} target="_blank" rel="noreferrer">{new URL(e.evidence.destination).hostname} · {decodeURIComponent(new URL(e.evidence.destination).pathname.split('/').filter(Boolean).at(-1)??'source')} ↗</a>}<div className="journal-context"><span title={e.topic}>{e.visitId===(held?pausedVisit:visitId)?'This encounter':e.topic}</span><button onClick={()=>void inspect(e.id)}>Inspect ↗</button></div></article>)}{!view?.entries.length&&<div className="journal-empty"><span>WAITING FOR AN ENCOUNTER</span><p>{request.loaded?'No entries match this view yet. The station continues independently.':'Connecting to the shared journal…'}</p></div>}</div>
 <div className="journal-status"><i className={`status-dot ${view?.narrator.state==='ready'?'live':view?.narrator.state==='generating'?'live':'stale'}`}/><span>{request.error||view?.narrator.message||'Connecting to recorded events…'}</span></div>
 {full&&<div className="button-row"><button disabled={!view?.entries.length} onClick={()=>{setBefore(view!.entries[0].at);setHeld(null);}}>Earlier entries</button><button onClick={()=>{setBefore('');setHeld(null);}}>Latest entries</button><small>{view?.total??0} entries retained · maximum {view?.retention??1500}</small></div>}
 {detailError&&<p role="alert">{detailError}</p>}
 {selected&&<div className="detail-backdrop" onClick={()=>setSelected(null)}><section className="detail-sheet" role="dialog" aria-modal="true" aria-label="Journal evidence" onClick={e=>e.stopPropagation()}><button className="close-detail" onClick={()=>setSelected(null)}>Close ×</button><span className="kicker">{selected.kind} / {selected.owner==='semantic-narrator'?'GENERATED NARRATION':'RECORDED EVENT'}</span><h2>{selected.topic}</h2>{selected.evidence.destination&&<p>Proposed destination: <a href={selected.evidence.destination} target="_blank" rel="noreferrer">{selected.evidence.destination} ↗</a></p>}<p className="detail-lead">{selected.text}</p><p>{time(selected.at)} · {selected.status} · {selected.owner==='semantic-narrator'?selected.model:'structured software event'}</p><div className="button-row">{selected.evidence.decision!==undefined&&<a className="button" href={actionLink(selected.evidence.runId,selected.evidence.decision)}>Inspect recorded action</a>}<a href={selected.evidence.url} target="_blank" rel="noreferrer">Encountered page ↗</a></div>{selected.evidence.memoryIds.length>0&&<><h3>Retrieved memories</h3>{selected.evidence.memoryIds.map(id=><a className="record-link" key={id} href={'/memory?id='+id}>Open linked encounter →</a>)}</>}{selected.context&&<><h3>Sources used for this entry</h3>{selected.context.sources.filter(s=>selected.evidence.sourceIds.includes(s.id)).map(s=><p key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a><br/>{s.passage}</p>)}{selected.evidence.sourceIds.includes('page')&&<details><summary>Captured page excerpt</summary><p>{selected.context.pageText}</p><small>Collected for the encounter at {time(selected.context.capturedAt)}.</small></details>}</>}<details><summary>Technical evidence and identifiers</summary><pre>{JSON.stringify(selected.evidence,null,2)}</pre><a href={'/api/journal/'+selected.id}>Complete journal record ↗</a></details><p className="muted">Narration explains recorded software events. It is not a measurement of biological thoughts. Proposed research stays separate from accepted and verified execution.</p></section></div>}
 </section>;
}
