import {useEffect,useState} from 'react';
import type {Circuit} from '../../shared/types';import type {MemoryView} from '../../shared/memory';
import {useExhibit} from '../useExhibit';import {usePresentation} from '../usePresentation';import {observationHealth} from '../../shared/observation';import {Apparatus} from '../Apparatus';import {DirectDesktop} from '../DirectDesktop';import {SpecimenView} from '../SpecimenView';import {DecodedInput} from '../DecodedInput';
import {Journal} from './Journal';import {usePublicData,source,actionLink,num} from './data';import {MemoryPage,ExperimentsPage,InsidePage,SpecimensPage} from './pages';import './showcase.css';import './laboratory.css';
export const NAV=[['/','Observe'],['/specimens','Specimens'],['/memory','Memory'],['/inside','Inside the system'],['/experiments','Experiments']];
export function Intro({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <div className="page-intro"><span className="kicker">{eyebrow}</span><h1>{title}</h1><div className="intro-copy">{children}</div></div>;}
export function ShowcaseApp(){const stream=useExhibit(),circuit=usePublicData<Circuit>('/api/circuit',60000).data,memory=usePublicData<MemoryView>('/api/memory',10000),[clock,setClock]=useState(0);useEffect(()=>{const t=setInterval(()=>setClock(v=>v+1),1000);return()=>clearInterval(t);},[]);void clock;
 const live=stream.live,now=stream.serverNow(),capture=live?.display??live?.desktop,health=observationHealth(stream.health,capture?.capturedAt,now,live?.state),presentation=usePresentation(live,false,health!=='live'),shown=presentation.live,s=shown?.snapshot??null,observation=shown?.observation,encounter=observation?.encounter,counts=live?.observation?.counters,age=capture?Math.max(0,(now-Date.parse(capture.capturedAt))/1000):null,path=location.pathname.replace(/\/$/,'')||'/',last=shown?.lastAction;
 useEffect(()=>{const titles:Record<string,string>={'/':'Observe','/specimens':'Specimens','/memory':'Memory','/inside':'Inside the system','/experiments':'Experiments','/journal':'Journal'};document.title=(titles[path]??'Not found')+' · Specimen Archive';},[path]);
 return <div className={"showcase page-"+(path==='/'?'observe':path.slice(1))}><a className="skip-link" href="#main-content">Skip to content</a><header className="site-header"><a className="site-brand" href="/" aria-label="Specimen Archive home"><span aria-hidden="true">✳</span><b>SPECIMEN<br/>ARCHIVE</b></a><nav aria-label="Main navigation">{NAV.map(([url,label])=><a key={url} href={url} aria-current={path===url?'page':undefined}>{label}</a>)}</nav><div className="social-links"><a href="https://x.com/SpecimenArchive" target="_blank" rel="noreferrer" aria-label="Specimen Archive on X">X ↗</a><a href="https://github.com/SpecimenArchive/Specimen-Archive" target="_blank" rel="noreferrer">GitHub ↗</a></div></header>
 <main id="main-content">{path==='/'?<><Intro eyebrow="AN OBSERVATION SERIES / LIVE FROM THE WINDOWS STATION" title="Specimen 01"><p>A larval circuit, a browser, an accumulating record. Observe the connections as they happen.</p><span className="species"><i>Platynereis dumerilii</i> · 72 hours post fertilisation <span>$LARVA</span></span></Intro>
 <div className="session-line" data-session-id={shown?.sessionId} data-run-id={shown?.runId} data-model-step={s?.seq}><span className={'live-pill '+health}><i className={'status-dot '+health}/><span className="exhibit-status">{health.toUpperCase()}</span></span><span>One shared session</span><span className="session-context">{encounter?.label??'Connecting to the observation station'}</span><span>Capture {num(age,1)} s ago</span></div>
 <div className="showcase-stage observation-stage"><Apparatus live={shown} desktopImage={presentation.desktopImage} health={health}/><DirectDesktop live={shown} desktopImage={presentation.desktopImage} health={health}/><Journal visitId={encounter?.visitId} objective={encounter?.reason}/><div className="showcase-connected connected-views"><section className="response-card specimen-panel" data-run-id={shown?.runId} data-model-step={s?.seq}><div className="card-heading"><span className="kicker">03 / SPECIMEN RESPONSE</span><span>Computed motion</span></div><div className="microscope"><SpecimenView snapshot={s} circuit={circuit}/>{health!=='live'&&<span className="held-badge">Held state · {health}</span>}</div><p>Generated specimen imagery responds to the same recorded motor state.</p></section>
 <section className="instruments-card signal-panel" data-run-id={shown?.runId} data-model-step={s?.seq}><div className="card-heading"><span className="kicker">04 / NEURAL INSTRUMENTS</span><span>{circuit?.nodes.length??'—'} cells · {circuit?.edges.length??'—'} connections</span></div><div className="instruments-body"><div className="sensory-image"><DecodedInput image={presentation.inputImage}/>{!presentation.inputImage&&<p>Waiting for a verified sensory image</p>}<small>The exact pixel input to this neural window</small></div><div className="signal-response"><div className="signal-pair"><p><span>Left sensory drive</span><b>{num(shown?.input?.left,3)}</b></p><p><span>Right sensory drive</span><b>{num(shown?.input?.right,3)}</b></p></div><div className="cell-strip" aria-label="Recorded activity of every implemented cell">{circuit?.nodes.map((n,i)=><a href={'/inside?cell='+n.id} key={n.id} title={n.name+' · '+num(s?.activity[i],3)} style={{height:(8+(s?.activity[i]??0)*64)+'px',opacity:.3+(s?.activity[i]??0)*.7}}/>)}</div><p className="signal-verdict">{last?.command.kind==='scroll'?`Motor output proposed ${last.command.wheelY} px wheel input.`:last?'The motor gate remained closed.':'Integrating the next recorded image.'}</p>{last&&<a href={actionLink(last.runId,last.decision)}>Follow this action through the system →</a>}</div></div></section></div></div>
 <div className="encounter-caption"><div><span className="kicker">OBSERVATION / CURRENT INVESTIGATION</span><h2>{encounter?.label??'Awaiting the next capture'}</h2><p>{encounter?.reason??'The supervisor is preparing an approved public destination.'}</p></div><div><span>{encounter?Math.max(0,Math.floor((now-Date.parse(encounter.enteredAt))/1000))+' seconds here':'Opening the station'}</span><p>{last?.receipt.reason??'Awaiting a verified outcome.'}</p><a href={encounter?.proposalId?'/journal?proposal='+encounter.proposalId:'/inside#supervisor'}>Why this next? →</a></div></div>
 <div className="showcase-journey" aria-label="Recent encounter journey">{observation?.journey?.slice(-5).map((e,i)=><a key={e.visitId} href={e.decision!==undefined?actionLink(e.runId,e.decision):'/journal'} title={e.label}><span>{String(i+1).padStart(2,'0')}</span><div><small>{e.kind==='coin'?'Token detail':e.kind==='knowledge'?'Primary reference':e.kind==='research'?'Larval research':'Explore'}</small><b>{e.label.replace(/ · pons$/i,'')}</b></div></a>)}</div>
 <div className="live-figures"><div><b>{counts?.moved??'—'}</b><span>verified movements</span></div><div><b>{counts?.uniquePages??'—'}</b><span>distinct pages</span></div><div><b>{memory.data?.stored??'—'}</b><span>stored encounters</span></div><div><b>{memory.data?.used??'—'}</b><span>memory uses</span></div><small>Movements & pages: this station session.<br/>Memory: the retained archive.</small></div>
 <div className="explore-links"><a href="/memory"><span className="kicker">COLLECTED ALONG THE WAY</span><h2>Memory</h2><p>Encounters, recalled evidence and the occasions it actually changed a supervisor decision.</p><b>Explore memory →</b></a><a href="/inside"><span className="kicker">FROM PIXELS TO AN ACTION</span><h2>Inside the system</h2><p>Trace a real capture through the circuit and see what Chrome received.</p><b>Follow the signal →</b></a><a href="/experiments"><span className="kicker">MEASURED, NOT ASSUMED</span><h2>Experiments</h2><p>Watch selected recordings and inspect successes, controls and failures.</p><b>View experiments →</b></a></div>
 <p className="narration-note">The journal is generated system narration grounded in recorded events and sources, not biological thoughts. The circuit proposes wheel direction; the supervisor selects pages.</p></>:path==='/memory'?<MemoryPage/>:path==='/inside'?<InsidePage live={live} circuit={circuit}/>:path==='/experiments'?<ExperimentsPage/>:path==='/specimens'?<SpecimensPage live={live} circuit={circuit} health={health}/>:path==='/journal'?<><Intro eyebrow="RETAINED FIELD NOTES" title="The journal"><p>Read the recorded encounters, sourced connections and open questions. Exploring this history never pauses the shared station.</p></Intro><Journal full visitId={encounter?.visitId}/></>:<Intro eyebrow="PAGE NOT FOUND" title="Return to the observation"><p>This destination is not part of the exhibit. <a href="/">Open the live station →</a></p></Intro>}</main>
 <footer className="site-footer"><a className="footer-brand" href="/">SPECIMEN ARCHIVE</a><p>A generated apparatus. A computed circuit.<br/>Real, recorded Windows execution.</p><div><a href="/inside#methods">Methods & assumptions</a><a href="/docs/WORKSHEET.html">Worksheet</a><a href={source(live?.sourceRevision,'server/exhibit/external-station.ts')}>Executed source ↗</a></div><span className="footer-session"><i className={'status-dot '+health}/>{health==='live'?'Station connected':health==='connecting'?'Connecting':`Station ${health}`}<small>Hosted on the Windows VM</small></span></footer></div>;
}
